@startuml
sprite $id1_icon_boundary_protocol [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFB99999999999999BFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF967777777777777767DFFFFFFFFFFFFFF
FFFFFFFFFFFFFFB6AFFCAFFFFFFFFFFC68FFFFFFFFFFFFFF
FFFFFFFFFFFFFF87FF77777FFFFFFFFF97FFFFFFFFFFFFFF
FFFFFFFFFFFFFF88F77458777777FFFFA6FFFFFFFFFFFFFF
FFFFFFFFFFFFFF88F74366666677FFFFA6FFFFFFFFFFFFFF
FFFFFFFFFFFFFF88D74344444467FFFFA6FFFFFFFFFFFFFF
FFFFFFFFFFFFFF88F77777777778887FA6FFFFFFFFFFFFFF
FFFFFFFFFFFFFF88F77777655555557BA6FFFFFFFFFFFFFF
FFFFFFFFFFFFFF88FFFF77544444326AA6FFFFFFFFFFFFFF
FFFFFFFFFFFFFF88FFFF77777786367FA6FFFFFFFFFFFFFF
FFFFFFFFFFFFFF88FFFF77777775677FA6FFFFFFFFFFFFFF
FFFFFFFFFFFFFF97FFFFFFFFFFFA9FFF87FFFFFFFFFFFFFF
FFFFFFFFFFFFFFD67BBBBBBBBBBBBBB96AFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFC7666666656666667AFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFDDDDDDB6CDDDDDFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFB6DFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFB6DFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFC6DFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFD859FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFA53236CFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFEEEEEEEEEEC5222226FEEEEFFFEEFFFFFFFFFF
FFFFFFFFFC766666666663222223666668FA668FFFFFFFFF
FFFFFFFFFEBAAAAAAAAA722222239AAAABFDAABFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF82222223BFFFFFFFFFFFFFFFFFFF
FFFFFFFFFDCCEFDCCCCD72222223ADCCCCCCCDFFFFFFFFFF
FFFFFFFFE866AF866666532222246666666667CFFFFFFFFF
FFFFFFFFFCCCDFDCCCCCB5222237CCCCCCCCCCFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFB63347EFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFBACFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_BOUNDARY_PROTOCOL(_color)                                 SPRITE_PUT(                                              id1_icon_boundary_protocol, _color)
!define ID1_ICON_BOUNDARY_PROTOCOL(_color, _scale)                         SPRITE_PUT(                                              id1_icon_boundary_protocol, _color, _scale)
!define ID1_ICON_BOUNDARY_PROTOCOL(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_BOUNDARY_PROTOCOL,         id1_icon_boundary_protocol, _color, _scale)
!define ID1_ICON_BOUNDARY_PROTOCOL(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_BOUNDARY_PROTOCOL,         id1_icon_boundary_protocol, _color, _scale, _shape)
!define ID1_ICON_BOUNDARY_PROTOCOL(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_BOUNDARY_PROTOCOL, _label, id1_icon_boundary_protocol, _color, _scale, _shape)
!define ID1_ICON_BOUNDARY_PROTOCOL(_alias)                                 ENTITY(rectangle,black,id1_icon_boundary_protocol,_alias,ID1_ICON_BOUNDARY_PROTOCOL)
!define ID1_ICON_BOUNDARY_PROTOCOL(_alias, _label)                         ENTITY(rectangle,black,id1_icon_boundary_protocol,_label, _alias,ID1_ICON_BOUNDARY_PROTOCOL)
!define ID1_ICON_BOUNDARY_PROTOCOL(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_boundary_protocol,_label, _alias,ID1_ICON_BOUNDARY_PROTOCOL)
!define ID1_ICON_BOUNDARY_PROTOCOL(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_boundary_protocol,_label, _alias,ID1_ICON_BOUNDARY_PROTOCOL
skinparam folderBackgroundColor<<ID1 ICON_BOUNDARY_PROTOCOL>> White
@enduml
