@startuml
sprite $id1_icon_auth0_authorization_server [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF74446FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF044444FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF1444444444FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF044444444444FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF44444444444FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF99FFF4444444449FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF8448D0444444444FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF8445BF444444444FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFEF0FFFF4444444BFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF04444444FFFFFFFFFFFF
FFFFFFFFFFFFFFDBBBBBBBBBBBBDFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF95555555555557AAAAABFFFFFFFFFFFFFF
FFFFFFFFFFFFFF94444444444445555557FFFFFFFFFFFFFF
FFFFFFFFFFFFFF95444444444444444446FEFFFFFFFFFFFF
FFFFFFFFFFFFFF95444444444444444446FEFFFFFFFFFFFF
FFFFFFFFFFFFFF95444444444444444446FEFFFFFFFFFFFF
FFFFFFFFFFFFFF95444444444444444446FEFFFFFFFFFFFF
FFFFFFFFFFFFFF95444444444444444446FEFFFFFFFFFFFF
FFFFFFFFFFFFFF95444444444444444446FEFFFFFFFFFFFF
FFFFFFFFFFFFFF95444444444444444446FEFFFFFFFFFFFF
FFFFFFFFFFFFFF95444444444444444446FEFFFFFFFFFFFF
FFFFFFFFFFFFFF95444444444444444446FEFFFFFFFFFFFF
FFFFFFFFFFFFFF94444444444444444446FEFFFFFFFFFFFF
FFFFFFFFFFFFFFA6666666666666666668FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFEEEEEEEEEEEEEEEEEEEFFFFFFFFFFFFFF
FFFFFFFFFFFFFFEDDDDDDDDB888888889DFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFA44444444444FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF844444444444DFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFB3444444444FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_color)                                 SPRITE_PUT(                                                       id1_icon_auth0_authorization_server, _color)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_color, _scale)                         SPRITE_PUT(                                                       id1_icon_auth0_authorization_server, _color, _scale)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_AUTH0_AUTHORIZATION_SERVER,         id1_icon_auth0_authorization_server, _color, _scale)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_AUTH0_AUTHORIZATION_SERVER,         id1_icon_auth0_authorization_server, _color, _scale, _shape)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_AUTH0_AUTHORIZATION_SERVER, _label, id1_icon_auth0_authorization_server, _color, _scale, _shape)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_alias)                                 ENTITY(rectangle,black,id1_icon_auth0_authorization_server,_alias,ID1_ICON_AUTH0_AUTHORIZATION_SERVER)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_alias, _label)                         ENTITY(rectangle,black,id1_icon_auth0_authorization_server,_label, _alias,ID1_ICON_AUTH0_AUTHORIZATION_SERVER)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_auth0_authorization_server,_label, _alias,ID1_ICON_AUTH0_AUTHORIZATION_SERVER)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_auth0_authorization_server,_label, _alias,ID1_ICON_AUTH0_AUTHORIZATION_SERVER
skinparam folderBackgroundColor<<ID1 ICON_AUTH0_AUTHORIZATION_SERVER>> White
@enduml
