@startuml
sprite $id1_icon_social_providers [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF77777FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF7777777FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF7764577FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF7732257FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF7622248FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFF7642367FFFFFFFFFFFFFFF
FFFFFFFFF77788777FFFFFFFFFFF67677FFFFFFFFFFFFFFF
FFFFFFFFF77755777FFFFFFFFFFA6F977FFFFFFFFFFFFFFF
FFFFFFFF7763223777FFFFFFFFF78FFFFFFFFFFFFFFFFFFF
FFFFFFFF7742222477FFFFFFFFB6CFFFFFFFFFFFFFFFFFFF
FFFFFFFF774222249FFFFFFFFF87FFFFFFFFFFFFFFFFFFFF
FFFFFFFF77522225EFFFFFFFFC6BFFFFFFFFFFFFFFFFFFFF
FFFFFFFF7775335769FFFFFFF87FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF777778BA67CFFFDC6AFFFFFFF7777777FFFFFFF
FFFFFFFFFF77776FFC76AB7665BFFFFFF777766777FFFFFF
FFFFFFFFFFFFFFFFFFF9658BB86BFFFFFF86322577FFFFFF
FFFFFFFFFFFFFFFFFFFF78FFFF87DDDDDD93222267FFFFFF
FFFFFFFFFFFFFFFFFFFD6BFFFFB566666662222268FFFFFF
FFFFFFFFFFFFFFFFFFC95BFFFFB6BCCCCCA3222267FFFFFF
FFFFFF777877FFFC976768FFFF87FFFFFF96323577FFFFFF
FFFFFF777564D97668BFB68BB85BFFFFF777767777FFFFFF
FFFFFF773225668BFFFFFB65676AFFFFFF7777777FFFFFFF
FFFFFF862223BFFFFFFFFF87EF96CFFFFFFFFFFFFFFFFFFF
FFFFFF762225AEFFFFFFFF79FFF77F8777FFFFFFFFFFFFFF
FFFFFF77645777FFFFFFFD6BFFFF655777FFFFFFFFFFFFFF
FFFFFF7777777FFFFFFFFB6DFF76422477FFFFFFFFFFFFFF
FFFFFFF77777FFFFFFFFF97FFF77322377FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF78FFF77422577FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF778F6AFFF77766777FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF777665CA7FF777777FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF775222477FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF762222257FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF852222248FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF762222258FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF773222377FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF777544677FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF777777777FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF77777FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_SOCIAL_PROVIDERS(_color)                                 SPRITE_PUT(                                             id1_icon_social_providers, _color)
!define ID1_ICON_SOCIAL_PROVIDERS(_color, _scale)                         SPRITE_PUT(                                             id1_icon_social_providers, _color, _scale)
!define ID1_ICON_SOCIAL_PROVIDERS(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_SOCIAL_PROVIDERS,         id1_icon_social_providers, _color, _scale)
!define ID1_ICON_SOCIAL_PROVIDERS(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_SOCIAL_PROVIDERS,         id1_icon_social_providers, _color, _scale, _shape)
!define ID1_ICON_SOCIAL_PROVIDERS(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_SOCIAL_PROVIDERS, _label, id1_icon_social_providers, _color, _scale, _shape)
!define ID1_ICON_SOCIAL_PROVIDERS(_alias)                                 ENTITY(rectangle,black,id1_icon_social_providers,_alias,ID1_ICON_SOCIAL_PROVIDERS)
!define ID1_ICON_SOCIAL_PROVIDERS(_alias, _label)                         ENTITY(rectangle,black,id1_icon_social_providers,_label, _alias,ID1_ICON_SOCIAL_PROVIDERS)
!define ID1_ICON_SOCIAL_PROVIDERS(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_social_providers,_label, _alias,ID1_ICON_SOCIAL_PROVIDERS)
!define ID1_ICON_SOCIAL_PROVIDERS(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_social_providers,_label, _alias,ID1_ICON_SOCIAL_PROVIDERS
skinparam folderBackgroundColor<<ID1 ICON_SOCIAL_PROVIDERS>> White
@enduml
