@startuml
sprite $id1_icon_server [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFD8888DFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF868869FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFE6AFF96FFFFFFFFFFFFFFF
FFFFFFFFFFFFDCCCCCCCCCCCCC96BBBB6ACCEFFFFFFFFFFF
FFFFFFFFFFFC6666666666666665666656669FFFFFFFFFFF
FFFFFFFFFFFB6BCCCCCCCCCCCCCDCCCCCCC78FFFFFFFFFFF
FFFFFFFFFFFB6DFFFFFCBFD5777777775DF88FFFFFFFFFFF
FFFFFFFFFFFB6CFFFFF74AA54444444467F88FFFFFFFFFFF
FFFFFFFFFFFB6CFFFFF97CB76666666677F88FFFFFFFFFFF
FFFFFFFFFFFB6DFFFFFFFFFCBBBBBBBBCFF88FFFFFFFFFFF
FFFFFFFFFFFC5788888888888888888888868FFFFFFFFFFF
FFFFFFFFFFFE974222222222222222222368BFFFFFFFFFFF
FFFFFFFFFFFFFD422222222222222222228FFFFFFFFFFFFF
FFFFFFFFFFFFDA422222222222222222227DEFFFFFFFFFFF
FFFFFFFFFFFC6654444444444444444444669FFFFFFFFFFF
FFFFFFFFFFFB6BDFFFFFFFFFFFFFFFFFFED78FFFFFFFFFFF
FFFFFFFFFFFB6DFFFFFCAED6777777776CF88FFFFFFFFFFF
FFFFFFFFFFFB6CFFFFF74AA53333333357F88FFFFFFFFFFF
FFFFFFFFFFFB6CFFFFFA7CB77777777777F88FFFFFFFFFFF
FFFFFFFFFFFB6DFFFFFFFFFDCCCCCCCCDFF88FFFFFFFFFFF
FFFFFFFFFFFC5788888888888888888888868FFFFFFFFFFF
FFFFFFFFFFFE974222222222222222222368BFFFFFFFFFFF
FFFFFFFFFFFFFD422222222222222222228FFFFFFFFFFFFF
FFFFFFFFFFFFDA422222222222222222227DEFFFFFFFFFFF
FFFFFFFFFFFC6654444444444444444444669FFFFFFFFFFF
FFFFFFFFFFFC6BDFFFFFFFFFFFFFFFFFFED78FFFFFFFFFFF
FFFFFFFFFFC96DFFFFFBAEFB99999999ADF87BFFFFFFFFFF
FFFFFFFB99745DFFFFF74AB64444444457F74599BFFFFFFF
FFFFFFFA77545DFFFFFA7CA76666666667F74477AFFFFFFF
FFFFFFFFFFA76DFFFFFFFFFDAAAAAAAABFF868FFFFFFFFFF
FFFFFFFFFFFC5788888888888888888888868FFFFFFFFFFF
FFFFFFFFFFFE988888888888888888888888BFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_SERVER(_color)                                 SPRITE_PUT(                                   id1_icon_server, _color)
!define ID1_ICON_SERVER(_color, _scale)                         SPRITE_PUT(                                   id1_icon_server, _color, _scale)
!define ID1_ICON_SERVER(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_SERVER,         id1_icon_server, _color, _scale)
!define ID1_ICON_SERVER(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_SERVER,         id1_icon_server, _color, _scale, _shape)
!define ID1_ICON_SERVER(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_SERVER, _label, id1_icon_server, _color, _scale, _shape)
!define ID1_ICON_SERVER(_alias)                                 ENTITY(rectangle,black,id1_icon_server,_alias,ID1_ICON_SERVER)
!define ID1_ICON_SERVER(_alias, _label)                         ENTITY(rectangle,black,id1_icon_server,_label, _alias,ID1_ICON_SERVER)
!define ID1_ICON_SERVER(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_server,_label, _alias,ID1_ICON_SERVER)
!define ID1_ICON_SERVER(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_server,_label, _alias,ID1_ICON_SERVER
skinparam folderBackgroundColor<<ID1 ICON_SERVER>> White
@enduml
