@startuml
sprite $id1_icon_user [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFDBAAAABDFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFC976667766679CFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFB7679BDF88FDB9767BFFFFFFFFFFFFFFF
FFFFFFFFFFFFFE867BAA96777779AAB768EFFFFFFFFFFFFF
FFFFFFFFFFFFC76BC97643322334679BB67CFFFFFFFFFFFF
FFFFFFFFFFFC67DA7532222222222357AD76CFFFFFFFFFFF
FFFFFFFFFFC68F96322222222222222369F86CFFFFFFFFFF
FFFFFFFFFE77F8522222223444222222259F77EFFFFFFFFF
FFFFFFFFF86D952222222578876322222259D68FFFFFFFFF
FFFFFFFFB6BA622222225877778622222226AB6BFFFFFFFF
FFFFFFFF77C732222223777FF778422222237B77FFFFFFFF
FFFFFFFC6B952222222587FFFF776222222259B6CFFFFFFF
FFFFFFF97A732222222587FFFF776222222237979FFFFFFF
FFFFFFF79A6222222224777FFF785222222226A97FFFFFFF
FFFFFFD6B942222222226777F77732222222249B6DFFFFFF
FFFFFFB6D632222222223777F77422222222237D6BFFFFFF
FFFFFFA6F732222222223677F77422222222237F6AFFFFFF
FFFFFFA78732222222367777F7776322222222787AFFFFFF
FFFFFFA7873222222368777FFF777742222222787AFFFFFF
FFFFFFA6F732222226777FFFFFF777732222237F6AFFFFFF
FFFFFFB6D63222224777FFFFFFFF77862222237D6BFFFFFF
FFFFFFD6B9422222677FFFFFFFFFF7773222249B6DFFFFFF
FFFFFFF79A62222377FFFFFFFFFFFF77422226A97FFFFFFF
FFFFFFF97A73222278777FFFFFF77777322237979FFFFFFF
FFFFFFFC6B9522224678888888888764222259B6CFFFFFFF
FFFFFFFF77C73222223455566555432222237B77FFFFFFFF
FFFFFFFFB6BA622222222222222222222226AB6BFFFFFFFF
FFFFFFFFF86D952222222222222222222259D68FFFFFFFFF
FFFFFFFFFE77F8522222222222222222259F77EFFFFFFFFF
FFFFFFFFFFC68F96322222222222222369F86CFFFFFFFFFF
FFFFFFFFFFFC67DA7532222222222357AD76CFFFFFFFFFFF
FFFFFFFFFFFFC76BC97643322334679BB67CFFFFFFFFFFFF
FFFFFFFFFFFFFE867BAA96777779AAB768EFFFFFFFFFFFFF
FFFFFFFFFFFFFFFB7679BDF88FDB9767BFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFC976667766679CFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFDBAAAABDFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_USER(_color)                                 SPRITE_PUT(                                 id1_icon_user, _color)
!define ID1_ICON_USER(_color, _scale)                         SPRITE_PUT(                                 id1_icon_user, _color, _scale)
!define ID1_ICON_USER(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_USER,         id1_icon_user, _color, _scale)
!define ID1_ICON_USER(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_USER,         id1_icon_user, _color, _scale, _shape)
!define ID1_ICON_USER(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_USER, _label, id1_icon_user, _color, _scale, _shape)
!define ID1_ICON_USER(_alias)                                 ENTITY(rectangle,black,id1_icon_user,_alias,ID1_ICON_USER)
!define ID1_ICON_USER(_alias, _label)                         ENTITY(rectangle,black,id1_icon_user,_label, _alias,ID1_ICON_USER)
!define ID1_ICON_USER(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_user,_label, _alias,ID1_ICON_USER)
!define ID1_ICON_USER(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_user,_label, _alias,ID1_ICON_USER
skinparam folderBackgroundColor<<ID1 ICON_USER>> White
@enduml
