@startuml
sprite $id1_icon_user [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF55FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF786344443687FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFA644444444444469FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF744444444444444447FFFFFFFFFFFFFFF
FFFFFFFFFFFFFF64444444444444444446FFFFFFFFFFFFFF
FFFFFFFFFFFFF6444444444444444444446FFFFFFFFFFFFF
FFFFFFFFFFFF644444444444444444444446FFFFFFFFFFFF
FFFFFFFFFFF74444444444444444444444447FFFFFFFFFFF
FFFFFFFFFFA444444444444FF4444444444449FFFFFFFFFF
FFFFFFFFFF644444444444FFFF444444444446FFFFFFFFFF
FFFFFFFFF8444444444444FFFF4444444444447FFFFFFFFF
FFFFFFFFF84444444444444FFF4444444444448FFFFFFFFF
FFFFFFFFF644444444444444F44444444444447FFFFFFFFF
FFFFFFFFF244444444444444F44444444444444FFFFFFFFF
FFFFFFFFF444444444444444F44444444444444FFFFFFFFF
FFFFFFFF5444444444444444F444444444444445FFFFFFFF
FFFFFFFF544444444444444FFF44444444444445FFFFFFFF
FFFFFFFFF444444444444FFFFFF444444444444FFFFFFFFF
FFFFFFFFF24444444444FFFFFFFF44444444444FFFFFFFFF
FFFFFFFFF6444444444FFFFFFFFFF4444444447FFFFFFFFF
FFFFFFFFF844444444FFFFFFFFFFFF444444448FFFFFFFFF
FFFFFFFFF844444444444FFFFFF444444444447FFFFFFFFF
FFFFFFFFFF6444444444444444444444444446FFFFFFFFFF
FFFFFFFFFFA444444444444444444444444449FFFFFFFFFF
FFFFFFFFFFF74444444444444444444444447FFFFFFFFFFF
FFFFFFFFFFFF644444444444444444444446FFFFFFFFFFFF
FFFFFFFFFFFFF6444444444444444444446FFFFFFFFFFFFF
FFFFFFFFFFFFFF64444444444444444446FFFFFFFFFFFFFF
FFFFFFFFFFFFFFF744444444444444447FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFA644444444444469FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF786344443687FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF55FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_USER(_color)                                 SPRITE_PUT(                                 id1_icon_user, _color)
!define ID1_ICON_USER(_color, _scale)                         SPRITE_PUT(                                 id1_icon_user, _color, _scale)
!define ID1_ICON_USER(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_USER,         id1_icon_user, _color, _scale)
!define ID1_ICON_USER(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_USER,         id1_icon_user, _color, _scale, _shape)
!define ID1_ICON_USER(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_USER, _label, id1_icon_user, _color, _scale, _shape)
!define ID1_ICON_USER(_alias)                                 ENTITY(rectangle,black,id1_icon_user,_alias,ID1_ICON_USER)
!define ID1_ICON_USER(_alias, _label)                         ENTITY(rectangle,black,id1_icon_user,_label, _alias,ID1_ICON_USER)
!define ID1_ICON_USER(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_user,_label, _alias,ID1_ICON_USER)
!define ID1_ICON_USER(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_user,_label, _alias,ID1_ICON_USER
skinparam folderBackgroundColor<<ID1 ICON_USER>> White
@enduml
