@startuml
sprite $id1_icon_cookie [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF6DFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF144FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF98AB6446FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF7445664447FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF74444444444ACFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF4444444444444FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF644444444444446FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF9444444444444445FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF0444444444444458BFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF844444456444444454466FFFFFFFFFFFFFFFFF
FFFFFFFFFF8444444586444444444445FA0FFFFFFFFFFFFF
FFFFFFFFFF444444445544444444444696458FFFFFFFFFFF
FFFFFFFFF6444456444444444444444554444FEFFFFFFFFF
FFFFFFFFF744458644444444444444444444449FFFFFFFFF
FFFFFFFFF74445544444444444444444444444AFFFFFFFFF
FFFFFFFFF744444444444445754444444444449FFFFFFFFF
FFFFFFFFF744444444544445764444444444447FFFFFFFFF
FFFFFFFFF544444445754444454444444445766FFFFFFFFF
FFFFFFFFFF444444455444444444444444457CFFFFFFFFFF
FFFFFFFFFFC764444444444444444444444441FFFFFFFFFF
FFFFFFFFFFF954444444444444444444444448FFFFFFFFFF
FFFFFFFFFFF24444444445654444554444443FFFFFFFFFFF
FFFFFFFFFFF84444444458754444764444448FFFFFFFFFFF
FFFFFFFFFFFFF44444444544444585444447FFFFFFFFFFFF
FFFFFFFFFFFFF3444444444444456544447FFFFFFFFFFFFF
FFFFFFFFFFFFFF34444444444444444446FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFB55444444444444447FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFD544444444444F9FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF7F4444444488FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF577775FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_COOKIE(_color)                                 SPRITE_PUT(                                   id1_icon_cookie, _color)
!define ID1_ICON_COOKIE(_color, _scale)                         SPRITE_PUT(                                   id1_icon_cookie, _color, _scale)
!define ID1_ICON_COOKIE(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_COOKIE,         id1_icon_cookie, _color, _scale)
!define ID1_ICON_COOKIE(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_COOKIE,         id1_icon_cookie, _color, _scale, _shape)
!define ID1_ICON_COOKIE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_COOKIE, _label, id1_icon_cookie, _color, _scale, _shape)
!define ID1_ICON_COOKIE(_alias)                                 ENTITY(rectangle,black,id1_icon_cookie,_alias,ID1_ICON_COOKIE)
!define ID1_ICON_COOKIE(_alias, _label)                         ENTITY(rectangle,black,id1_icon_cookie,_label, _alias,ID1_ICON_COOKIE)
!define ID1_ICON_COOKIE(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_cookie,_label, _alias,ID1_ICON_COOKIE)
!define ID1_ICON_COOKIE(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_cookie,_label, _alias,ID1_ICON_COOKIE
skinparam folderBackgroundColor<<ID1 ICON_COOKIE>> White
@enduml
