@startuml
sprite $id1_icon_user_db [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFEDCCDEFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFCA987776677789ACFFFFFFFFFFFFFFFF
FFFFFFFFFFFFB8654332222222222334568BFFFFFFFFFFFF
FFFFFFFFFFB64322222222222222222222346BFFFFFFFFFF
FFFFFFFFFD5222222222222222222222222225DFFFFFFFFF
FFFFFFFFFA4222222222222222222222222224AFFFFFFFFF
FFFFFFFFFA5432222222222222222222222345AFFFFFFFFF
FFFFFFFFFA6D864332222222222222233468D6AFFFFFFFFF
FFFFFFFFFA6FFFFB9876555555556789BFFFF6AFFFFFFFFF
FFFFFFFFFA6FFFFFFFC4FFFFFFFF4CFFFFFFF6AFFFFFFFFF
FFFFFFFFFA6FFFFFFFFFFFFFFFFFFFFFD9BFF6AFFFFFFFFF
FFFFFFFFFA6FFFFFFFFFFFFC99888BFFA7AFF6AFFFFFFFFF
FFFFFFFFFA6FFFFFFFFFFFFB77788BFFFFFFF6AFFFFFFFFF
FFFFFFFFFA5AFFFFFFFFFFFFFFFFFFFFFFFFA5AFFFFFFFFF
FFFFFFFFFA5678BDFFFFFFFFFFFFFFFFDB8765AFFFFFFFFF
FFFFFFFFFA7C976677899AAAAAA998776679C7AFFFFFFFFF
FFFFFFFFFA6FFFDB9887776666777889BDFFF6AFFFFFFFFF
FFFFFFFFFA6FFFFFFFFFFFFEEFFFFFFFFFFFF6AFFFFFFFFF
FFFFFFFFFA6FFFFFFFFFFFFFFFFFFFFFB8AFF6AFFFFFFFFF
FFFFFFFFFA6FFFFFFFFFFFFB87777AFFA8BFF6AFFFFFFFFF
FFFFFFFFFA6FFFFFFFFFFFFB8889ACFFFFFFF6AFFFFFFFFF
FFFFFFFFFA59DFFFFFFFFFFFFFFFFFFFFFFD95AFFFFFFFFF
FFFFFFFFFA6668ACEFFFFFFFFFFFFFFECA8666AFFFFFFFFF
FFFFFFFFFA7DA8666778899999988776668AD7AFFFFFFFFF
FFFFFFFFFA6FFFFCB98877777777889BCFFFF6AFFFFFFFFF
FFFFFFFFFA6FFFFFFFFFFFFFFFFFFFFFFFFFF6AFFFFFFFFF
FFFFFFFFFA6FFFFFFFFFFFFFFFFEDEFFB79FF6AFFFFFFFFF
FFFFFFFFFA6FFFFFFFFFFFFA77666AFFB9CFF6AFFFFFFFFF
FFFFFFFFFA6FFFFFFFFFFFFCAAABBDFFFFFFF6AFFFFFFFFF
FFFFFFFFFC68DFFFFFFFFFFFFFFFFFFFFFFD86CFFFFFFFFF
FFFFFFFFFFA6679BDFFFFFFFFFFFFFFDB9766AFFFFFFFFFF
FFFFFFFFFFFEA8666778899999988776668AEFFFFFFFFFFF
FFFFFFFFFFFFFFFCBA988777777889ABCFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_USER_DB(_color)                                 SPRITE_PUT(                                    id1_icon_user_db, _color)
!define ID1_ICON_USER_DB(_color, _scale)                         SPRITE_PUT(                                    id1_icon_user_db, _color, _scale)
!define ID1_ICON_USER_DB(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_USER_DB,         id1_icon_user_db, _color, _scale)
!define ID1_ICON_USER_DB(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_USER_DB,         id1_icon_user_db, _color, _scale, _shape)
!define ID1_ICON_USER_DB(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_USER_DB, _label, id1_icon_user_db, _color, _scale, _shape)
!define ID1_ICON_USER_DB(_alias)                                 ENTITY(rectangle,black,id1_icon_user_db,_alias,ID1_ICON_USER_DB)
!define ID1_ICON_USER_DB(_alias, _label)                         ENTITY(rectangle,black,id1_icon_user_db,_label, _alias,ID1_ICON_USER_DB)
!define ID1_ICON_USER_DB(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_user_db,_label, _alias,ID1_ICON_USER_DB)
!define ID1_ICON_USER_DB(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_user_db,_label, _alias,ID1_ICON_USER_DB
skinparam folderBackgroundColor<<ID1 ICON_USER_DB>> White
@enduml
