@startuml
sprite $id1_icon_desktop_app [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFCBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCFFFFFFFF
FFFFFFE8666666666666666666666666666666668EFFFFFF
FFFFFF96BDEEEEEEEEEEEEEEEEEEEEEEEEEEEEDB69FFFFFF
FFFFFF78FEBBBBBBBBBBBBBBBBBBBBBBBBBBBBEF87FFFFFF
FFFFFF79F966666666666666666666666666669F97FFFFFF
FFFFFF79F88EDDDDDDDDDDDFFEDDDDDDDDDDE88F97FFFFFF
FFFFFF79F88FFFFFFFFD888767988FFFFFFFF88F97FFFFFF
FFFFFF79F88FFFFFFF7766742576677FFFFFF88F97FFFFFF
FFFFFF79F88FFFFF77773232223237777FFFF88F97FFFFFF
FFFFFF79F88FFFFF77762222222236777FFFF88F97FFFFFF
FFFFFF79F88FFFFF76322222222222367FFFF88F97FFFFFF
FFFFFF79F88FFFFF85222222222222267FFFF88F97FFFFFF
FFFFFF79F88FFFF7762222357522223777FFF88F97FFFFFF
FFFFFF79F88FFFF77422226FFD52222577FFF88F97FFFFFF
FFFFFF79F88FFFF85222238FFF72222267FFF88F97FFFFFF
FFFFFF79F88FFFF763222275FF52222477FFF88F97FFFFFF
FFFFFF79F88FFFF7762222368632223777FFF88F97FFFFFF
FFFFFF79F88FFFF785222222322222267FFFF88F97FFFFFF
FFFFFF79F88FFFFF75222222222222367FFFF88F97FFFFFF
FFFFFF79F88FFFFF77752222222226777FFFF88F97FFFFFF
FFFFFF79F88FFFFF77772222222237777FFFF88F97FFFFFF
FFFFFF79F88FFFFFFF7755632465677FFFFFF88F97FFFFFF
FFFFFF79F88FFFFFFFF8888657888EFFFFFFF88F97FFFFFF
FFFFFF79F88FFFFFFFFFFFD674DFFFFFFFFFF88F97FFFFFF
FFFFFF79F867777777777777777777777777768F97FFFFFF
FFFFFF78FDAAAAAAAAAAAAAAAAAAAAAAAAAAAADF87FFFFFF
FFFFFF87DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD78FFFFFF
FFFFFFD7677777777776777777776777777777767DFFFFFF
FFFFFFFEA99999999A769999999967A99999999AEFFFFFFF
FFFFFFFFFFFFFFFFFF88FFFFFFFF87FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFE6AFFFFFFFFA6EFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFB6CDDDDDDDDC6BFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFA566666666665AFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFEBBBBBBBBBBBBEFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_DESKTOP_APP(_color)                                 SPRITE_PUT(                                        id1_icon_desktop_app, _color)
!define ID1_ICON_DESKTOP_APP(_color, _scale)                         SPRITE_PUT(                                        id1_icon_desktop_app, _color, _scale)
!define ID1_ICON_DESKTOP_APP(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_DESKTOP_APP,         id1_icon_desktop_app, _color, _scale)
!define ID1_ICON_DESKTOP_APP(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_DESKTOP_APP,         id1_icon_desktop_app, _color, _scale, _shape)
!define ID1_ICON_DESKTOP_APP(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_DESKTOP_APP, _label, id1_icon_desktop_app, _color, _scale, _shape)
!define ID1_ICON_DESKTOP_APP(_alias)                                 ENTITY(rectangle,black,id1_icon_desktop_app,_alias,ID1_ICON_DESKTOP_APP)
!define ID1_ICON_DESKTOP_APP(_alias, _label)                         ENTITY(rectangle,black,id1_icon_desktop_app,_label, _alias,ID1_ICON_DESKTOP_APP)
!define ID1_ICON_DESKTOP_APP(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_desktop_app,_label, _alias,ID1_ICON_DESKTOP_APP)
!define ID1_ICON_DESKTOP_APP(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_desktop_app,_label, _alias,ID1_ICON_DESKTOP_APP
skinparam folderBackgroundColor<<ID1 ICON_DESKTOP_APP>> White
@enduml
