@startuml
sprite $id1_icon_credential_user [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF866666666666666666666668FFFFFFFFFFFF
FFFFFFFFFFFE68AAAAAAAAAAAAAAAAAAAA86EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFDA99ADFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFD86677668DFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFC76AEFFEA67CFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFE77EF8888FE77EFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFF96DF775577FD69FFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFF79F77322377F97FFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFC6CF85222258FC6CFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFB6DF85222258FD6BFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFB6DF77322377FD6BFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFD6BB74222247BB6DFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFF77F42222224F77FFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFB672222222276BFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFA52222222259FFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFA53222235AFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFF965569FFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFAFFAFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFEA999999999999AEFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFD87777777777778DFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFD88888888888888DFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFD88888888888888DFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE68AAAAAAAAAAAAAAAAAAAA86EFFFFFFFFFFF
FFFFFFFFFFFF866666666666666666666668FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_CREDENTIAL_USER(_color)                                 SPRITE_PUT(                                            id1_icon_credential_user, _color)
!define ID1_ICON_CREDENTIAL_USER(_color, _scale)                         SPRITE_PUT(                                            id1_icon_credential_user, _color, _scale)
!define ID1_ICON_CREDENTIAL_USER(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_CREDENTIAL_USER,         id1_icon_credential_user, _color, _scale)
!define ID1_ICON_CREDENTIAL_USER(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_CREDENTIAL_USER,         id1_icon_credential_user, _color, _scale, _shape)
!define ID1_ICON_CREDENTIAL_USER(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_CREDENTIAL_USER, _label, id1_icon_credential_user, _color, _scale, _shape)
!define ID1_ICON_CREDENTIAL_USER(_alias)                                 ENTITY(rectangle,black,id1_icon_credential_user,_alias,ID1_ICON_CREDENTIAL_USER)
!define ID1_ICON_CREDENTIAL_USER(_alias, _label)                         ENTITY(rectangle,black,id1_icon_credential_user,_label, _alias,ID1_ICON_CREDENTIAL_USER)
!define ID1_ICON_CREDENTIAL_USER(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_credential_user,_label, _alias,ID1_ICON_CREDENTIAL_USER)
!define ID1_ICON_CREDENTIAL_USER(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_credential_user,_label, _alias,ID1_ICON_CREDENTIAL_USER
skinparam folderBackgroundColor<<ID1 ICON_CREDENTIAL_USER>> White
@enduml
