@startuml
sprite $id1_icon_api [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFBAEFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFC97667AFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF967885335ABFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFE76AFFDF632389FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF86CFFF77773239EFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFB6BFFFFF7776225668CFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF78FFFFFFF777427BA76AFFFFFFFFFFF
FFFFFFFFFFFFFFFEB6BFFFFFFFF7765AFFF96AFFFFFFFFFF
FFFFFFFFFFFFFFA667DFFFFFFFFF77777FFF96EFFFFFFFFF
FFFFFFFFFFFFFA69DFFFFFFFFFFF7777FFFFD6AFFFFFFFFF
FFFFFFFFFFFFD69FFFFFFFFFFFFFFFFFFFFFF79FFFFFFFFF
FFFFFFFFFFFC66EFFFFFFFFFFFFFFFFFFFFFF78FFFFFFFFF
FFFFFFD8777646FFFFFFFFFFFFFFFFFFFFFFF6AFFFFFFFFF
FFFFFFB6888846EFFFFFFFFFFFFFFFFFFFFFA6CFFFFFFFFF
FFFFFFB6EFFFA69FFFFFFFFFFFFFFFFFFFFD68FFFFFFFFFF
FFFFFFB6DFFFFA69EFFFFFFFFFFFFFFFFDA67EFFFFFFFFFF
FFFFFFB6DFFFFFA667777777777777777669EFFFFFFFFFFF
FFFFFFB6DFFFFFFDA999999999999999ABDFFFFFFFFFFFFF
FFFFFFB6DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFB6DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFB6DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFB6DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFB6DFFFFF777777777FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFB6DFFFF7777777777FFFFFFDBBCEFFFFFFFFFFFFFF
FFFFFFB6DFFF77764322377FFFFFF845568DFFFFFFFFFFFF
FFFFFFB6DFFF77522222277FFFFFF7444447DFFFFFFFFFFF
FFFFFFB6DFF776222222377FF988864444448FFFFFFFFFFF
FFFFFFB6EFFFA4222222377FF988864444445DFFFFFFFFFF
FFFFFFB6999993222222377FFFFFF744444448999EFFFFFF
FFFFFFD8777773222222377FFFFFF744444446778DFFFFFF
FFFFFFFFFFFFA4222222377FFBAAA74444445CFFFFFFFFFF
FFFFFFFFFFF776222222377FE866654444447FFFFFFFFFFF
FFFFFFFFFFFF77422222277FFFEEF7444445BFFFFFFFFFFF
FFFFFFFFFFFF77753222377FFFFFF744446BFFFFFFFFFFFF
FFFFFFFFFFFFF7777655677FFFFFFB999BFFFFFFFFFFFFFF
FFFFFFFFFFFFFF777788777FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_API(_color)                                 SPRITE_PUT(                                id1_icon_api, _color)
!define ID1_ICON_API(_color, _scale)                         SPRITE_PUT(                                id1_icon_api, _color, _scale)
!define ID1_ICON_API(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_API,         id1_icon_api, _color, _scale)
!define ID1_ICON_API(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_API,         id1_icon_api, _color, _scale, _shape)
!define ID1_ICON_API(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_API, _label, id1_icon_api, _color, _scale, _shape)
!define ID1_ICON_API(_alias)                                 ENTITY(rectangle,black,id1_icon_api,_alias,ID1_ICON_API)
!define ID1_ICON_API(_alias, _label)                         ENTITY(rectangle,black,id1_icon_api,_label, _alias,ID1_ICON_API)
!define ID1_ICON_API(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_api,_label, _alias,ID1_ICON_API)
!define ID1_ICON_API(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_api,_label, _alias,ID1_ICON_API
skinparam folderBackgroundColor<<ID1 ICON_API>> White
@enduml
