@startuml
sprite $id1_icon_generic_enterprise_directory [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFD77DFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7777FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF86DD68FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF96BDDB69FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFA6AC77CA6AFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFB69C7447C96BFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFC68D852258D86CFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFE77F85222258F77EFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF77D9622222269D77FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF86C963222222369C68FFFFFFFFFFFFFFF
FFFFFFFFFFFFFF96BA732222222237AB69FFFFFFFFFFFFFF
FFFFFFFFFFFFFA6AB74222222222247BA6AFFFFFFFFFFFFF
FFFFFFFFFFFFB69D7422222553222247D96BFFFFFFFFFFFF
FFFFFFFFFFFD68D852222268862222258D86DFFFFFFFFFFF
FFFFFFFFFFE77F85222463777736422258F77EFFFFFFFFFF
FFFFFFFFFF86D9622227745776477222269D68FFFFFFFFFF
FFFFFFFFF86CA6322226853663585222236AC68FFFFFFFFF
FFFFFFFF96BB732222255346743542222237BB69FFFFFFFF
FFFFFFFB6AC74222225636877863552222247CA6BFFFFFFF
FFFFFFD68F7622222374587777864732222267F86DFFFFFF
FFFFFFE76BD75222225368888886352222257DB67EFFFFFF
FFFFFFFF86AD863222223455554322222368DA68FFFFFFFF
FFFFFFFFF968F8632222222222222222368F869FFFFFFFFF
FFFFFFFFFFB67D97422222222222222479D76BFFFFFFFFFF
FFFFFFFFFFFC77CB7422222222222247BC77CFFFFFFFFFFF
FFFFFFFFFFFFD76BCF522222222225FCB67DFFFFFFFFFFFF
FFFFFFFFFFFFFF869D863222222368D968FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFA68F9632222369F86AFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFB67DA7422479D76BFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFC77CB7557BC77CFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFE86AD88DA68EFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF969FF969FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFA6886AFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFB66BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_color)                                 SPRITE_PUT(                                                         id1_icon_generic_enterprise_directory, _color)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_color, _scale)                         SPRITE_PUT(                                                         id1_icon_generic_enterprise_directory, _color, _scale)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_GENERIC_ENTERPRISE_DIRECTORY,         id1_icon_generic_enterprise_directory, _color, _scale)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_GENERIC_ENTERPRISE_DIRECTORY,         id1_icon_generic_enterprise_directory, _color, _scale, _shape)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_GENERIC_ENTERPRISE_DIRECTORY, _label, id1_icon_generic_enterprise_directory, _color, _scale, _shape)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_alias)                                 ENTITY(rectangle,black,id1_icon_generic_enterprise_directory,_alias,ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_alias, _label)                         ENTITY(rectangle,black,id1_icon_generic_enterprise_directory,_label, _alias,ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_generic_enterprise_directory,_label, _alias,ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_generic_enterprise_directory,_label, _alias,ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY
skinparam folderBackgroundColor<<ID1 ICON_GENERIC_ENTERPRISE_DIRECTORY>> White
@enduml
