@startuml
sprite $id1_icon_auth0 [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFD99999999999999999999DFFFFFFFFFFFFF
FFFFFFFFFFFFF9333333333333333333339FFFFFFFFFFFFF
FFFFFFFFFFFFC7222222222332222222227CFFFFFFFFFFFF
FFFFFFFFFFFFF4222222222442222222224FFFFFFFFFFFFF
FFFFFFFFFFFFA3222222222662222222223AFFFFFFFFFFFF
FFFFFFFFFFFD722222222237732222222227DFFFFFFFFFFF
FFFFFFFFFFFF522222222247742222222225FFFFFFFFFFFF
FFFFFFFFFFFA322222222267762222222223AFFFFFFFFFFF
FFFFFFFFFFD72222222223777732222222227DFFFFFFFFFF
FFFFFFFFFFF52222222224777742222222225FFFFFFFFFFF
FFFFFFFFFFA33444444446777764444444433AFFFFFFFFFF
FFFFFFFFFF8224788888877777788888874228FFFFFFFFFF
FFFFFFFFFB622236777FFFFFFFFFF777632226BFFFFFFFFF
FFFFFFFFFF62222257777FFFFFF77775222226FFFFFFFFFF
FFFFFFFFFF52222224777FFFFFF77742222225FFFFFFFFFF
FFFFFFFFFF62222222367FFFFFF76322222226FFFFFFFFFF
FFFFFFFFFC62222222258FFFFFF85222222226CFFFFFFFFF
FFFFFFFFFF83222222277F7777F77222222238FFFFFFFFFF
FFFFFFFFFFB32222224777777777742222223BFFFFFFFFFF
FFFFFFFFFFF52222225877744777852222225FFFFFFFFFFF
FFFFFFFFFFF93222227776322367772222239FFFFFFFFFFF
FFFFFFFFFFFF522224775222222577422225FFFFFFFFFFFF
FFFFFFFFFFFFA4222574222222224752224AFFFFFFFFFFFF
FFFFFFFFFFFFE8322532222222222352238EFFFFFFFFFFFF
FFFFFFFFFFFFFF83222222222222222238FFFFFFFFFFFFFF
FFFFFFFFFFFFFFC942222222222222249CFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFC63222222222236CFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF842222222248FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFDA52222225ADFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFD632236DFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF8448FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFBBFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_AUTH0(_color)                                 SPRITE_PUT(                                  id1_icon_auth0, _color)
!define ID1_ICON_AUTH0(_color, _scale)                         SPRITE_PUT(                                  id1_icon_auth0, _color, _scale)
!define ID1_ICON_AUTH0(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_AUTH0,         id1_icon_auth0, _color, _scale)
!define ID1_ICON_AUTH0(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_AUTH0,         id1_icon_auth0, _color, _scale, _shape)
!define ID1_ICON_AUTH0(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_AUTH0, _label, id1_icon_auth0, _color, _scale, _shape)
!define ID1_ICON_AUTH0(_alias)                                 ENTITY(rectangle,black,id1_icon_auth0,_alias,ID1_ICON_AUTH0)
!define ID1_ICON_AUTH0(_alias, _label)                         ENTITY(rectangle,black,id1_icon_auth0,_label, _alias,ID1_ICON_AUTH0)
!define ID1_ICON_AUTH0(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_auth0,_label, _alias,ID1_ICON_AUTH0)
!define ID1_ICON_AUTH0(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_auth0,_label, _alias,ID1_ICON_AUTH0
skinparam folderBackgroundColor<<ID1 ICON_AUTH0>> White
@enduml
