@startuml
sprite $id1_icon_api_related [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFDBDFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFC987678CFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFD8678864346BEFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFB67BFFEC6522496FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFB68FFFF877762238DFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFE78FFFFFFF7785224ADDFFFFFFFFFFFFFF
FFFFFFFFFFFFFF96EFFFFFFFF7774225667AFFFFFFFFFFFF
FFFFFFFFFFFFFE69FFFFFFFFFF77623ACB867CFFFFFFFFFF
FFFFFFFFFFFFFB6DFFFFFFFFFFF77469FFFD76DFFFFFFFFF
FFFFFFFFFFFB867FFFFFFFFFFFF777777FFFF77FFFFFFFFF
FFFFFFFFFF8679CFFFFFFFFFFFF77777FFFFFC6BFFFFFFFF
FFFFFFFFF86BFFFFFFFFFFFFFFFFFFFFFFFFFF78FFFFFFFF
FFFFFFFFB6BFFFFFFFFFFFFFFFFFFFFFFFFFFF97FFFFFFFF
FFFFFFFF87FFFFFFFFFFFFFFFFFFFFFFFFFFFF97FFFFFFFF
FFFFFFFF79FFFFFFFFFFFFFFFFFFFFFFFFFFFF87FFFFFFFF
FFFFFFFF79FFFFFFFFFFFFFFFFFFFFFFFFFFFF79FFFFFFFF
FFFFFFFF87FFFFFFFFFFFFFFFFFFFFFFFFFFFA6CFFFFFFFF
FFFFFFFFB6BFFFFFFFFFFFFFFFFFFFFFFFFFC69FFFFFFFFF
FFFFFFFFF86BFFFFFFFFFFFFFFFFFFFFFFFA68FFFFFFFFFF
FFFFFFFFFF867999999999999999999998768FFFFFFFFFFF
FFFFFFFFFFFB87777777777777777777779CFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_API_RELATED(_color)                                 SPRITE_PUT(                                        id1_icon_api_related, _color)
!define ID1_ICON_API_RELATED(_color, _scale)                         SPRITE_PUT(                                        id1_icon_api_related, _color, _scale)
!define ID1_ICON_API_RELATED(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_API_RELATED,         id1_icon_api_related, _color, _scale)
!define ID1_ICON_API_RELATED(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_API_RELATED,         id1_icon_api_related, _color, _scale, _shape)
!define ID1_ICON_API_RELATED(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_API_RELATED, _label, id1_icon_api_related, _color, _scale, _shape)
!define ID1_ICON_API_RELATED(_alias)                                 ENTITY(rectangle,black,id1_icon_api_related,_alias,ID1_ICON_API_RELATED)
!define ID1_ICON_API_RELATED(_alias, _label)                         ENTITY(rectangle,black,id1_icon_api_related,_label, _alias,ID1_ICON_API_RELATED)
!define ID1_ICON_API_RELATED(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_api_related,_label, _alias,ID1_ICON_API_RELATED)
!define ID1_ICON_API_RELATED(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_api_related,_label, _alias,ID1_ICON_API_RELATED
skinparam folderBackgroundColor<<ID1 ICON_API_RELATED>> White
@enduml
