@startuml
sprite $id1_icon_cookie [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFDB988BFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFB8667767FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFB768AD9FB6DFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFE868CDF577F78FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFD76BBA654359B679CFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFD67EA64222237AC867FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFE77FA5222222247CFA6FFFFFFFFFFFFFFFFFFF
FFFFFFFFFF856F5222222222346C6CFFFFFFFFFFFFFFFFFF
FFFFFFFFFB6B962222222222226978FFFFFFFFFFFFFFFFFF
FFFFFFFFF78B6322222222222248867BDC9BFFFFFFFFFFFF
FFFFFFFFA6D24222222222222236DC766666DFFFFFFFFFFF
FFFFFFFF78A62222222222222223699DBCE77BFFFFFFFFFF
FFFFFFFD6AA422222232222222222467B94E8678EFFFFFFF
FFFFFFFB6F73222222222222222222234368AB96BFFFFFFF
FFFFFFF979622222222222222222222222357FF79FFFFFFF
FFFFFFF87A5222322222222222222222222235B78FFFFFFF
FFFFFFF88A5222222222222222222222222224C88FFFFFFF
FFFFFFF88A5222222222222222222222222224B88FFFFFFF
FFFFFFF87A5222222222222232222222222224A78FFFFFFF
FFFFFFF9785222222232222222222222222236979FFFFFFF
FFFFFFFB6F6222222222222222222222222237F6BFFFFFFF
FFFFFFFD6A9322222222222222222222222235A6DFFFFFFF
FFFFFFFF78A62222222222222222222222225A87FFFFFFFF
FFFFFFFFA6F63222222222222222222222246D6AFFFFFFFF
FFFFFFFFF78A522222222332222232222226B87FFFFFFFFF
FFFFFFFFFB6BF4222222222222223222225AB6BFFFFFFFFF
FFFFFFFFFF86F6422222222222222222259E68FFFFFFFFFF
FFFFFFFFFFE77F65222222222222222369F77EFFFFFFFFFF
FFFFFFFFFFFD67FC6322222222222247AD76DFFFFFFFFFFF
FFFFFFFFFFFFD76BD6542222222346FBB67DFFFFFFFFFFFF
FFFFFFFFFFFFFE868BAF76555567ABD868EFFFFFFFFFFFFF
FFFFFFFFFFFFFFFB768AF8AAAA8FA867BFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFB866778877668BFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFDB988889BDFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_COOKIE(_color)                                 SPRITE_PUT(                                   id1_icon_cookie, _color)
!define ID1_ICON_COOKIE(_color, _scale)                         SPRITE_PUT(                                   id1_icon_cookie, _color, _scale)
!define ID1_ICON_COOKIE(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_COOKIE,         id1_icon_cookie, _color, _scale)
!define ID1_ICON_COOKIE(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_COOKIE,         id1_icon_cookie, _color, _scale, _shape)
!define ID1_ICON_COOKIE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_COOKIE, _label, id1_icon_cookie, _color, _scale, _shape)
!define ID1_ICON_COOKIE(_alias)                                 ENTITY(rectangle,black,id1_icon_cookie,_alias,ID1_ICON_COOKIE)
!define ID1_ICON_COOKIE(_alias, _label)                         ENTITY(rectangle,black,id1_icon_cookie,_label, _alias,ID1_ICON_COOKIE)
!define ID1_ICON_COOKIE(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_cookie,_label, _alias,ID1_ICON_COOKIE)
!define ID1_ICON_COOKIE(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_cookie,_label, _alias,ID1_ICON_COOKIE
skinparam folderBackgroundColor<<ID1 ICON_COOKIE>> White
@enduml
