@startuml
sprite $id1_icon_cli_script [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF1222222222222222222222222221FFFFFFFFFF
FFFFFFFFF444444444444444444444444444444FFFFFFFFF
FFFFFFFFF444444444444444444444444444444FFFFFFFFF
FFFFFFFFF444444444444444444444444444444FFFFFFFFF
FFFFFFFFF444444444444444444444444444444FFFFFFFFF
FFFFFFFFF444443344444444444444444444444FFFFFFFFF
FFFFFFFFF444443134444444444444444444444FFFFFFFFF
FFFFFFFFF444444313444444444444444444444FFFFFFFFF
FFFFFFFFF444444431344444444444444444444FFFFFFFFF
FFFFFFFFF444444452144444444444444444444FFFFFFFFF
FFFFFFFFF444444431344444444444444444444FFFFFFFFF
FFFFFFFFF444444313444444444444444444444FFFFFFFFF
FFFFFFFFF444443134444444444444444444444FFFFFFFFF
FFFFFFFFF444443344444211124444444444444FFFFFFFFF
FFFFFFFFF444444444444444444444444444444FFFFFFFFF
FFFFFFFFF444444444444444444444444444444FFFFFFFFF
FFFFFFFFF444444444444444444444444444444FFFFFFFFF
FFFFFFFFF444444444444444444444444444444FFFFFFFFF
FFFFFFFFF444444444444444444444444444444FFFFFFFFF
FFFFFFFFFF1222222222222222222222222221FFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_CLI_SCRIPT(_color)                                 SPRITE_PUT(                                       id1_icon_cli_script, _color)
!define ID1_ICON_CLI_SCRIPT(_color, _scale)                         SPRITE_PUT(                                       id1_icon_cli_script, _color, _scale)
!define ID1_ICON_CLI_SCRIPT(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_CLI_SCRIPT,         id1_icon_cli_script, _color, _scale)
!define ID1_ICON_CLI_SCRIPT(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_CLI_SCRIPT,         id1_icon_cli_script, _color, _scale, _shape)
!define ID1_ICON_CLI_SCRIPT(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_CLI_SCRIPT, _label, id1_icon_cli_script, _color, _scale, _shape)
!define ID1_ICON_CLI_SCRIPT(_alias)                                 ENTITY(rectangle,black,id1_icon_cli_script,_alias,ID1_ICON_CLI_SCRIPT)
!define ID1_ICON_CLI_SCRIPT(_alias, _label)                         ENTITY(rectangle,black,id1_icon_cli_script,_label, _alias,ID1_ICON_CLI_SCRIPT)
!define ID1_ICON_CLI_SCRIPT(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_cli_script,_label, _alias,ID1_ICON_CLI_SCRIPT)
!define ID1_ICON_CLI_SCRIPT(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_cli_script,_label, _alias,ID1_ICON_CLI_SCRIPT
skinparam folderBackgroundColor<<ID1 ICON_CLI_SCRIPT>> White
@enduml
