@startuml
sprite $id1_icon_dashboard [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFD8888888888888888888888888888888888DFFFFFF
FFFFFFB6888888888888888888888888888888886BFFFFFF
FFFFFFB6B7BB7CB8DFFFFFFFFFFFFFFFFFFFFFFE6BFFFFFF
FFFFFFB6A6AA6B96CFFFFFFFFFFFFFFFFFFFFFFD6BFFFFFF
FFFFFFB6AAAAABAABBBBBBBBBBBBBBBBBBBBBBBA6BFFFFFF
FFFFFFB5666666666666666666666666666666665BFFFFFF
FFFFFFB6DEEBCFFFFFFFFEEEEEEEEEEEEEEEEEED6BFFFFFF
FFFFFFB6DFC57854444478FFFFFFFFFFFFFFFFFD6BFFFFFF
FFFFFFB6DFC67765555579FFFFFFFFFFFFFFFFFD6BFFFFFF
FFFFFFB6CDDCDDFFFFFFFDDDDDDDDDDDDDDDDDDC6BFFFFFF
FFFFFFB5666666666666666666666666666666665BFFFFFF
FFFFFFB6BBBBBBBBBBBB69BBBBBBBBBBBBBBBBBB6BFFFFFF
FFFFFFB6DFFFFFFFFFFE6BFFFFFDBBBBBBFFFFFD6BFFFFFF
FFFFFFB6DFFCBBBBBEFD6BFFFF7777777777FFFD6BFFFFFF
FFFFFFB6DFD766667BFD6BFFF776333333777FFD6BFFFFFF
FFFFFFB6DFFEDDDDEFFD6BFFF774224322587FFD6BFFFFFF
FFFFFFB6DFFBAAAAADFD6BFFF773226522477FFD6BFFFFFF
FFFFFFB6DFE766667BFD6BFFF763577765377FFD6BFFFFFF
FFFFFFB6DFFFFFFFFFFD6BFFF862368752277FFD6BFFFFFF
FFFFFFB6DFEA99999DFD6BFFF762267742377FFD6BFFFFFF
FFFFFFB6DFE877777CFD6BFFF774352352577FFD6BFFFFFF
FFFFFFB6DFFFFFFFFFFD6BFFF777422235777FFD6BFFFFFF
FFFFFFB6DFE988888CFD6BFFF77775236777FFFD6BFFFFFF
FFFFFFB6DFE878888CFD6BFFFFF77767777FFFFD6BFFFFFF
FFFFFFB6DFFFFFFFFFFD6BFFFFFF777777FFFFFD6BFFFFFF
FFFFFFB6EFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFE6BFFFFFF
FFFFFFB6888888888888578888888888888888886BFFFFFF
FFFFFFD8888888888888888888888888888888888DFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_DASHBOARD(_color)                                 SPRITE_PUT(                                      id1_icon_dashboard, _color)
!define ID1_ICON_DASHBOARD(_color, _scale)                         SPRITE_PUT(                                      id1_icon_dashboard, _color, _scale)
!define ID1_ICON_DASHBOARD(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_DASHBOARD,         id1_icon_dashboard, _color, _scale)
!define ID1_ICON_DASHBOARD(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_DASHBOARD,         id1_icon_dashboard, _color, _scale, _shape)
!define ID1_ICON_DASHBOARD(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_DASHBOARD, _label, id1_icon_dashboard, _color, _scale, _shape)
!define ID1_ICON_DASHBOARD(_alias)                                 ENTITY(rectangle,black,id1_icon_dashboard,_alias,ID1_ICON_DASHBOARD)
!define ID1_ICON_DASHBOARD(_alias, _label)                         ENTITY(rectangle,black,id1_icon_dashboard,_label, _alias,ID1_ICON_DASHBOARD)
!define ID1_ICON_DASHBOARD(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_dashboard,_label, _alias,ID1_ICON_DASHBOARD)
!define ID1_ICON_DASHBOARD(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_dashboard,_label, _alias,ID1_ICON_DASHBOARD
skinparam folderBackgroundColor<<ID1 ICON_DASHBOARD>> White
@enduml
