@startuml
sprite $id1_icon_auth0_authorization_server [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD868EFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFB67A67BFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF968FBF869FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFC76AA6469A68DFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFA67F052235FD76BFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFA695742222247F86BFFFFFFF
FFFFFFFFFFFE98888888888876063222222237F6AFFFFFFF
FFFFFFFFFFFC57777777777776B62222222236A6EFFFFFFF
FFFFFFFFFFFB6DFFFFFFFFFBB78F322222224B88FFFFFFFF
FFFFFFFFFFFB6CFFFFF97CA76663522222225F6AFFFFFFFF
FFFFFFFFFFFB6CFFFFF74AA6445D622222226A6DFFFFFFFF
FFFFFFFFFFFB6DFFFFFCAEFF2F78F3222224D88FFFFFFFFF
FFFFFFFFFFFB6CFFFFFFFFFFFF9636666666F6AFFFFFFFFF
FFFFFFFFFFFC6655555555555555BFFFFFFEA6DFFFFFFFFF
FFFFFFFFFFFFCA422222222222234444446668FFFFFFFFFF
FFFFFFFFFFFFFC422222223333322222227DCEFFFFFFFFFF
FFFFFFFFFFFFFC422222257647742222227FFFFFFFFFFFFF
FFFFFFFFFFFFFC422222378537862222227FFFFFFFFFFFFF
FFFFFFFFFFFFFC422222355324552222227FFFFFFFFFFFFF
FFFFFFFFFFFFFC422222552222363222227FFFFFFFFFFFFF
FFFFFFFFFFFFFC422222585222673222227FFFFFFFFFFFFF
FFFFFFFFFFFFFC422222374232662222227FFFFFFFFFFFFF
FFFFFFFFFFFFFC422222254675442222227FFFFFFFFFFFFF
FFFFFFFFFFFFFC422222224786322222227FFFFFFFFFFFFF
FFFFFFFFFFFFFC422222222352222222227FFFFFFFFFFFFF
FFFFFFFFFFFFFD422222222222222222227FFFFFFFFFFFFF
FFFFFFFFFFFE984222222222222222222369CFFFFFFFFFFF
FFFFFFFFFFFC5777777777777777777777768FFFFFFFFFFF
FFFFFFFFFFFC6DFEEEEFFFEDBBBBBBBBBFF88FFFFFFFFFFF
FFFFFFFFFFA65DFFFFF97CB76666666677F858EFFFFFFFFF
FFFFFFFA77545DFFFFF74AA64444444457F74477AFFFFFFF
FFFFFFFB9A745DFFFFFCBFC6777777777FF74599BFFFFFFF
FFFFFFFFFFC96CDDDDDDDDDDEEEEEEEEEDE77BFFFFFFFFFF
FFFFFFFFFFFC6666666666666666666666669FFFFFFFFFFF
FFFFFFFFFFFFCBBBBBBBBBBBBBBBBBBBBBBBDFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_color)                                 SPRITE_PUT(                                                       id1_icon_auth0_authorization_server, _color)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_color, _scale)                         SPRITE_PUT(                                                       id1_icon_auth0_authorization_server, _color, _scale)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_AUTH0_AUTHORIZATION_SERVER,         id1_icon_auth0_authorization_server, _color, _scale)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_AUTH0_AUTHORIZATION_SERVER,         id1_icon_auth0_authorization_server, _color, _scale, _shape)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_AUTH0_AUTHORIZATION_SERVER, _label, id1_icon_auth0_authorization_server, _color, _scale, _shape)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_alias)                                 ENTITY(rectangle,black,id1_icon_auth0_authorization_server,_alias,ID1_ICON_AUTH0_AUTHORIZATION_SERVER)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_alias, _label)                         ENTITY(rectangle,black,id1_icon_auth0_authorization_server,_label, _alias,ID1_ICON_AUTH0_AUTHORIZATION_SERVER)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_auth0_authorization_server,_label, _alias,ID1_ICON_AUTH0_AUTHORIZATION_SERVER)
!define ID1_ICON_AUTH0_AUTHORIZATION_SERVER(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_auth0_authorization_server,_label, _alias,ID1_ICON_AUTH0_AUTHORIZATION_SERVER
skinparam folderBackgroundColor<<ID1 ICON_AUTH0_AUTHORIZATION_SERVER>> White
@enduml
