@startuml
sprite $id1_icon_attributes [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFECCCCCCCCCCCCCCCCCCCCCCCCEFFFFFFFFFFF
FFFFFFFFFFFA666666666666666666666666AFFFFFFFFFFF
FFFFFFFFFFF97DCCCCCCCCCCCCCCCCCCCCD79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFFFFFFFFFFF79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFFFFFFFFFFF79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFFFFFFFFFFF79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFE7788877FF79FFFFFFFFFFF
FFFFFFFFFFF97FFB88888888BE7655577FF79FFFFFFFFFFF
FFFFFFFFFFF97FFB88888888BE7544577FF79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFD7788877FF79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFE77777777F79FFFFFFFFFFF
FFFFFFFFFFF97FFDBBBBBBBBDE77666677F79FFFFFFFFFFF
FFFFFFFFFFF97FFA66666666AE75444457F79FFFFFFFFFFF
FFFFFFFFFFF97FFFDDDDDDDDFE77777778F79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFF77777771F79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFF777777FFF79FFFFFFFFFFF
FFFFFFFFFFF97FFA76666666AE754577FFF79FFFFFFFFFFF
FFFFFFFFFFF97FFDAAAAAAAACE766777FFF79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFE777777FFF79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFE77888877F79FFFFFFFFFFF
FFFFFFFFFFF97FFB88888888BE76555567F79FFFFFFFFFFF
FFFFFFFFFFF97FFB88888888BE75555567F79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFD77888877F79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFE7777FFFFF79FFFFFFFFFFF
FFFFFFFFFFF97FFDBBBBBBBBDE7777FFFFF79FFFFFFFFFFF
FFFFFFFFFFF97FFA66666666AE7567FFFFF79FFFFFFFFFFF
FFFFFFFFFFF97FFFDDDDDDDDFE7777FFFFF79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFF7777FFFFF79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFFFFFFFFFFF79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFFFFFFFFFFF79FFFFFFFFFFF
FFFFFFFFFFF97FFFFFFFFFFFFFFFFFFFFFF79FFFFFFFFFFF
FFFFFFFFFFF97DCCCCCCCCCCCCCCCCCCCCD79FFFFFFFFFFF
FFFFFFFFFFFA666666666666666666666666AFFFFFFFFFFF
FFFFFFFFFFFECCCCCCCCCCCCCCCCCCCCCCCCEFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_ATTRIBUTES(_color)                                 SPRITE_PUT(                                       id1_icon_attributes, _color)
!define ID1_ICON_ATTRIBUTES(_color, _scale)                         SPRITE_PUT(                                       id1_icon_attributes, _color, _scale)
!define ID1_ICON_ATTRIBUTES(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_ATTRIBUTES,         id1_icon_attributes, _color, _scale)
!define ID1_ICON_ATTRIBUTES(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_ATTRIBUTES,         id1_icon_attributes, _color, _scale, _shape)
!define ID1_ICON_ATTRIBUTES(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_ATTRIBUTES, _label, id1_icon_attributes, _color, _scale, _shape)
!define ID1_ICON_ATTRIBUTES(_alias)                                 ENTITY(rectangle,black,id1_icon_attributes,_alias,ID1_ICON_ATTRIBUTES)
!define ID1_ICON_ATTRIBUTES(_alias, _label)                         ENTITY(rectangle,black,id1_icon_attributes,_label, _alias,ID1_ICON_ATTRIBUTES)
!define ID1_ICON_ATTRIBUTES(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_attributes,_label, _alias,ID1_ICON_ATTRIBUTES)
!define ID1_ICON_ATTRIBUTES(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_attributes,_label, _alias,ID1_ICON_ATTRIBUTES
skinparam folderBackgroundColor<<ID1 ICON_ATTRIBUTES>> White
@enduml
