@startuml
sprite $id1_icon_spa [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFCBBBBBBBBBBBBBBBBBBBBBBBBBBCFFFFFFFFFF
FFFFFFFFFF7666666666666666666666666667FFFFFFFFFF
FFFFFFFFFE6AEDDDDDDDDDDDDDDDDDEEEEEEA6EFFFFFFFFF
FFFFFFFFFE6AFFFFFFFFFFFFFC78FDAAAAAFA6EFFFFFFFFF
FFFFFFFFFE6AFFFFFFFFFFFFFB56FB77777EA6EFFFFFFFFF
FFFFFFFFFE6AFFFFFFFFFFFFFFABFFFFFFFFA6EFFFFFFFFF
FFFFFFFFFE6AFFFFFFFFFFFFFFFFFFFFFFFFA6EFFFFFFFFF
FFFFFFFFFF6444444444444444444444444446FFFFFFFFFF
FFFFFFFFFF5222222222222222222222222225FFFFFFFFFF
FFFFFFFFFF5222222222222222222222222225FFFFFFFFFF
FFFFFFFFFF5222222222222222222222222225FFFFFFFFFF
FFFFFFFFFF5222222222222222222222222225FFFFFFFFFF
FFFFFFFFFF5222222222222222222222222225FFFFFFFFFF
FFFFFFFFFF5222222222222222222222222225FFFFFFFFFF
FFFFFFFFFF5222222222222222222222222225FFFFFFFFFF
FFFFFFFFFF5222222222222222222222222225FFFFFFFFFF
FFFFFFFFFF5222222222222222222222222225FFFFFFFFFF
FFFFFFFFFF6333333333333333333333333336FFFFFFFFFF
FFFFFFFFFE68BBBBBBBBBBBBBBBBBBBBBBBB86EFFFFFFFFF
FFFFFFFFFE6AFFFFFFFFFFFFFFFFFFFFFFFFA6EFFFFFFFFF
FFFFFFFFFE6AFFFFFFFFFFFFFFFFFFFFFFFFA6EFFFFFFFFF
FFFFFFFFFE6AFFFFFFFFFA9999AFFFFFFFFFA6EFFFFFFFFF
FFFFFFFFFE6AFFFFFFFFE877778EFFFFFFFFA6EFFFFFFFFF
FFFFFFFFFE6AFFFFFFFFFFFFFFFFFFFFFFFFA6EFFFFFFFFF
FFFFFFFFFE6AFFFFFFFFFFFFFFFFFFFFFFFFA6EFFFFFFFFF
FFFFFFFFFE6AFFFFFFFFFFFFFFFFFFFFFFFFA6EFFFFFFFFF
FFFFFFFFFE6AFC777777779FF977777777CFA6EFFFFFFFFF
FFFFFFFFFE6AFDA9AAAAA9BFFB9AAAAA9ADFA6EFFFFFFFFF
FFFFFFFFFE6AFFFFFFFFFFFFFFFFFFFFFFFFA6EFFFFFFFFF
FFFFFFFFFE6AFD98999998AFFA89999989DFA6EFFFFFFFFF
FFFFFFFFFE6AFC877777779FF977777778CFA6EFFFFFFFFF
FFFFFFFFFE6AFFFFFFFFFFFFFFFFFFFFFFFFA6EFFFFFFFFF
FFFFFFFFFE6AFFFFFFFFFFFFFFFFFFFFFFFFA6EFFFFFFFFF
FFFFFFFFFE6AEDDDDDDDDDDDDDDDDDDDDDDEA6EFFFFFFFFF
FFFFFFFFFF7666666666666666666666666667FFFFFFFFFF
FFFFFFFFFFCBBBBBBBBBBBBBBBBBBBBBBBBBBCFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_SPA(_color)                                 SPRITE_PUT(                                id1_icon_spa, _color)
!define ID1_ICON_SPA(_color, _scale)                         SPRITE_PUT(                                id1_icon_spa, _color, _scale)
!define ID1_ICON_SPA(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_SPA,         id1_icon_spa, _color, _scale)
!define ID1_ICON_SPA(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_SPA,         id1_icon_spa, _color, _scale, _shape)
!define ID1_ICON_SPA(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_SPA, _label, id1_icon_spa, _color, _scale, _shape)
!define ID1_ICON_SPA(_alias)                                 ENTITY(rectangle,black,id1_icon_spa,_alias,ID1_ICON_SPA)
!define ID1_ICON_SPA(_alias, _label)                         ENTITY(rectangle,black,id1_icon_spa,_label, _alias,ID1_ICON_SPA)
!define ID1_ICON_SPA(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_spa,_label, _alias,ID1_ICON_SPA)
!define ID1_ICON_SPA(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_spa,_label, _alias,ID1_ICON_SPA
skinparam folderBackgroundColor<<ID1 ICON_SPA>> White
@enduml
