@startuml
sprite $id1_icon_web_app [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFA7777777777777777777777777777AFFFFFFFFF
FFFFFFFFF869999999999999999999999999968FFFFFFFFF
FFFFFFFFF88FFFFFFFFFFFFFFFBBFFFFFFFFF88FFFFFFFFF
FFFFFFFFF88FFFFFFFFFFFFFFC55CE87777AF88FFFFFFFFF
FFFFFFFFF88FFFFFFFFFFFFFFD66DFA9999BF88FFFFFFFFF
FFFFFFFFF88FFFFFFFFFFFFFFFFFFFFFFFFFF88FFFFFFFFF
FFFFFFFFF879999999999999999999999999978FFFFFFFFF
FFFFFFFFF857777777777777777777777777758FFFFFFFFF
FFFFFFFFF88FFFFFFFFFFFFBBFFFFFFFFFFFF88FFFFFFFFF
FFFFFFFFF88FFFFFFF08767777677FFFFFFFF88FFFFFFFFF
FFFFFFFFF88FFFFFF77778733687777FFFFFF88FFFFFFFFF
FFFFFFFFF88FFFFFF77435422353377FFFFFF88FFFFFFFFF
FFFFFFFFF88FFF77786222222222268777FFF88FFFFFFFFF
FFFFFFFFF88FFF77775222222222247777FFF88FFFFFFFFF
FFFFFFFFF88FFF77422222222222222377FFF88FFFFFFFFF
FFFFFFFFF88FFF77322222222222222267FFF88FFFFFFFFF
FFFFFFFFF88FF7774222223554222224777FF88FFFFFFFFF
FFFFFFFFF88FF7774222239FFA422223777FF88FFFFFFFFF
FFFFFFFFF88FF773222226FFFE722222377FF88FFFFFFFFF
FFFFFFFFF88FF772222226CFFF722222267FF88FFFFFFFFF
FFFFFFFFF88FF776322224CFFD522222577FF88FFFFFFFFF
FFFFFFFFF88FF7785222225885222224877FF88FFFFFFFFF
FFFFFFFFF88FFF77322222223222222377FFF88FFFFFFFFF
FFFFFFFFF88FFF77322222222222222277FFF88FFFFFFFFF
FFFFFFFFF88FFF77654222222222235677FFF88FFFFFFFFF
FFFFFFFFF88FFF77786222222222268777FFF88FFFFFFFFF
FFFFFFFFF88FFFFFF773233222322677FFFFF88FFFFFFFFF
FFFFFFFFF88FFFFFF77667622676677FFFFFF88FFFFFFFFF
FFFFFFFFF88FFFFFF77777766777777FFFFFF88FFFFFFFFF
FFFFFFFFF88FFFFFFFFFFFFAAFFFFFFFFFFFF88FFFFFFFFF
FFFFFFFFF869999999999999999999999999968FFFFFFFFF
FFFFFFFFFA7777777777777777777777777777AFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_WEB_APP(_color)                                 SPRITE_PUT(                                    id1_icon_web_app, _color)
!define ID1_ICON_WEB_APP(_color, _scale)                         SPRITE_PUT(                                    id1_icon_web_app, _color, _scale)
!define ID1_ICON_WEB_APP(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_WEB_APP,         id1_icon_web_app, _color, _scale)
!define ID1_ICON_WEB_APP(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_WEB_APP,         id1_icon_web_app, _color, _scale, _shape)
!define ID1_ICON_WEB_APP(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_WEB_APP, _label, id1_icon_web_app, _color, _scale, _shape)
!define ID1_ICON_WEB_APP(_alias)                                 ENTITY(rectangle,black,id1_icon_web_app,_alias,ID1_ICON_WEB_APP)
!define ID1_ICON_WEB_APP(_alias, _label)                         ENTITY(rectangle,black,id1_icon_web_app,_label, _alias,ID1_ICON_WEB_APP)
!define ID1_ICON_WEB_APP(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_web_app,_label, _alias,ID1_ICON_WEB_APP)
!define ID1_ICON_WEB_APP(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_web_app,_label, _alias,ID1_ICON_WEB_APP
skinparam folderBackgroundColor<<ID1 ICON_WEB_APP>> White
@enduml
