@startuml
sprite $id1_icon_generic_enterprise_directory [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFBBFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFA44AFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFB4444BFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFB544445BFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF54444445FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF6444444446FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF744444444447FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF84444444444448FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFA44444444444444AFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFB4444444444444444BFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFB544444444444444445BFFFFFFFFFFFFFF
FFFFFFFFFFFFFF54444444444444444445FFFFFFFFFFFFFF
FFFFFFFFFFFFF6444444444444444444446FFFFFFFFFFFFF
FFFFFFFFFFFF744444444444444444444447FFFFFFFFFFFF
FFFFFFFFFFF84444444444444444444444448FFFFFFFFFFF
FFFFFFFFFFB44444444444444444444444444BFFFFFFFFFF
FFFFFFFFFF4444444444444444444444444444FFFFFFFFFF
FFFFFFFFFFC44444444444444444444444444CFFFFFFFFFF
FFFFFFFFFFFB544444444444444444444445BFFFFFFFFFFF
FFFFFFFFFFFFF6444444444444444444446FFFFFFFFFFFFF
FFFFFFFFFFFFFF74444444444444444447FFFFFFFFFFFFFF
FFFFFFFFFFFFFFF844444444444444448FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFAF444444444444FAFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFB544444444445BFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF6444444446FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF74444447FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF944449FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFB55BFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFEEFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_color)                                 SPRITE_PUT(                                                         id1_icon_generic_enterprise_directory, _color)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_color, _scale)                         SPRITE_PUT(                                                         id1_icon_generic_enterprise_directory, _color, _scale)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_GENERIC_ENTERPRISE_DIRECTORY,         id1_icon_generic_enterprise_directory, _color, _scale)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_GENERIC_ENTERPRISE_DIRECTORY,         id1_icon_generic_enterprise_directory, _color, _scale, _shape)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_GENERIC_ENTERPRISE_DIRECTORY, _label, id1_icon_generic_enterprise_directory, _color, _scale, _shape)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_alias)                                 ENTITY(rectangle,black,id1_icon_generic_enterprise_directory,_alias,ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_alias, _label)                         ENTITY(rectangle,black,id1_icon_generic_enterprise_directory,_label, _alias,ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_generic_enterprise_directory,_label, _alias,ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY)
!define ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_generic_enterprise_directory,_label, _alias,ID1_ICON_GENERIC_ENTERPRISE_DIRECTORY
skinparam folderBackgroundColor<<ID1 ICON_GENERIC_ENTERPRISE_DIRECTORY>> White
@enduml
