@startuml
sprite $id1_icon_access_token [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFBBFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF9669FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFD76AA67DFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFA67CFFC76AFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFE869EB77BE968EFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFC76BF875578FB67CFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFA68DE77422477ED86AFFFFFFFFFFFFFFF
FFFFFFFFFFFFFD869FA7632222367AF968DFFFFFFFFFFFFF
FFFFFFFFFFFFB67BF87422222222478FB76BFFFFFFFFFFFF
FFFFFFFFFFF968EC7632222332222367CE869FFFFFFFFFFF
FFFFFFFFFD76AF97522224777742222579FA67DFFFFFFFFF
FFFFFFFFA67CF8742222477667742222478FC76AFFFFFFFF
FFFFFFF869EB763222226773377622222367BE968FFFFFFF
FFFFFFC6AF9752222223777557773222222579FA6CFFFFFF
FFFFFFF79F7422222223777777773222222247F97FFFFFFF
FFFFFFF87F8422222222687777862222222248F78FFFFFFF
FFFFFFFB6C8622222222377777732222222268C6BFFFFFFF
FFFFFFFF69C73222222223677632222222237C96FFFFFFFF
FFFFFFFF87F74222222222588522222222247F78FFFFFFFF
FFFFFFFFB6D86222222222587522222222268D6BFFFFFFFF
FFFFFFFFE6AC732222222258732222222237CA6EFFFFFFFF
FFFFFFFFF87F742222222258742222222247F78FFFFFFFFF
FFFFFFFFFB6D862222222258742222222268D6BFFFFFFFFF
FFFFFFFFFE6AB7322222225874222222237BA6EFFFFFFFFF
FFFFFFFFFF87F7422222225873222222247F78FFFFFFFFFF
FFFFFFFFFFB6D8522222225874222222258D6BFFFFFFFFFF
FFFFFFFFFFE6AB72222222254222222227BA6EFFFFFFFFFF
FFFFFFFFFFF88F74222222222222222247F88FFFFFFFFFFF
FFFFFFFFFFFA6D85222222222222222258D6AFFFFFFFFFFF
FFFFFFFFFFFD6AB744444444444444447BA6DFFFFFFFFFFF
FFFFFFFFFFFF88F888888888888888888F88FFFFFFFFFFFF
FFFFFFFFFFFFA6EFFFFFFFFFFFFFFFFFFE6AFFFFFFFFFFFF
FFFFFFFFFFFFD6677777777777777777766DFFFFFFFFFFFF
FFFFFFFFFFFFFB99999999999999999999BFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_ACCESS_TOKEN(_color)                                 SPRITE_PUT(                                         id1_icon_access_token, _color)
!define ID1_ICON_ACCESS_TOKEN(_color, _scale)                         SPRITE_PUT(                                         id1_icon_access_token, _color, _scale)
!define ID1_ICON_ACCESS_TOKEN(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_ACCESS_TOKEN,         id1_icon_access_token, _color, _scale)
!define ID1_ICON_ACCESS_TOKEN(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_ACCESS_TOKEN,         id1_icon_access_token, _color, _scale, _shape)
!define ID1_ICON_ACCESS_TOKEN(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_ACCESS_TOKEN, _label, id1_icon_access_token, _color, _scale, _shape)
!define ID1_ICON_ACCESS_TOKEN(_alias)                                 ENTITY(rectangle,black,id1_icon_access_token,_alias,ID1_ICON_ACCESS_TOKEN)
!define ID1_ICON_ACCESS_TOKEN(_alias, _label)                         ENTITY(rectangle,black,id1_icon_access_token,_label, _alias,ID1_ICON_ACCESS_TOKEN)
!define ID1_ICON_ACCESS_TOKEN(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_access_token,_label, _alias,ID1_ICON_ACCESS_TOKEN)
!define ID1_ICON_ACCESS_TOKEN(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_access_token,_label, _alias,ID1_ICON_ACCESS_TOKEN
skinparam folderBackgroundColor<<ID1 ICON_ACCESS_TOKEN>> White
@enduml
