@startuml
sprite $id1_icon_mobile_app [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF444444FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF444444444444FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF444444444444FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF44444444444444FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF4444444444444444FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFE4444444444444444FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFA4444444554444444DFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFC4444457A97544444FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFB444448FFFD744444BFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF044445AFFFF954444AFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF044445AFFFF954444AFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFB444448FFFD744444BFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFC4444457A97544444FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFA4444444554444444DFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFE4444444444444444FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF4444444444444444FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF44444444444444FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF444444444444FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF444444444444FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF8448FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF444444FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF444444FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF444444FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFD9449DFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_MOBILE_APP(_color)                                 SPRITE_PUT(                                       id1_icon_mobile_app, _color)
!define ID1_ICON_MOBILE_APP(_color, _scale)                         SPRITE_PUT(                                       id1_icon_mobile_app, _color, _scale)
!define ID1_ICON_MOBILE_APP(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_MOBILE_APP,         id1_icon_mobile_app, _color, _scale)
!define ID1_ICON_MOBILE_APP(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_MOBILE_APP,         id1_icon_mobile_app, _color, _scale, _shape)
!define ID1_ICON_MOBILE_APP(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_MOBILE_APP, _label, id1_icon_mobile_app, _color, _scale, _shape)
!define ID1_ICON_MOBILE_APP(_alias)                                 ENTITY(rectangle,black,id1_icon_mobile_app,_alias,ID1_ICON_MOBILE_APP)
!define ID1_ICON_MOBILE_APP(_alias, _label)                         ENTITY(rectangle,black,id1_icon_mobile_app,_label, _alias,ID1_ICON_MOBILE_APP)
!define ID1_ICON_MOBILE_APP(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_mobile_app,_label, _alias,ID1_ICON_MOBILE_APP)
!define ID1_ICON_MOBILE_APP(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_mobile_app,_label, _alias,ID1_ICON_MOBILE_APP
skinparam folderBackgroundColor<<ID1 ICON_MOBILE_APP>> White
@enduml
