@startuml
sprite $id1_icon_server [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFC1444444441CFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF844444444444FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944444444444FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFEEEEFFEFA99999999AFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFA7777777777777777778FFFFFFFFFFFFFF
FFFFFFFFFFFFFF94444444444444444446FFFFFFFFFFFFFF
FFFFFFFFFFFFFF95555555555555555557FFFFFFFFFFFFFF
FFFFFFFFFFFFFFDAAAAAAAAAAAAAAAAAABFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFB3444444443BFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF844444444444FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF944444444444FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFB99999999BFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFA7777777777777777778FFFFFFFFFFFFFF
FFFFFFFFFFFFFF94444444444444444446FFFFFFFFFFFFFF
FFFFFFFFFFFFFF95555555555555555557FFFFFFFFFFFFFF
FFFFFFFFFFFFFFCAAAAAAAAAAAAAAAAAABFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF9777777777CFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF844444444444DFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF844444444444EFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFB888888888EFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_SERVER(_color)                                 SPRITE_PUT(                                   id1_icon_server, _color)
!define ID1_ICON_SERVER(_color, _scale)                         SPRITE_PUT(                                   id1_icon_server, _color, _scale)
!define ID1_ICON_SERVER(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_SERVER,         id1_icon_server, _color, _scale)
!define ID1_ICON_SERVER(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_SERVER,         id1_icon_server, _color, _scale, _shape)
!define ID1_ICON_SERVER(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_SERVER, _label, id1_icon_server, _color, _scale, _shape)
!define ID1_ICON_SERVER(_alias)                                 ENTITY(rectangle,black,id1_icon_server,_alias,ID1_ICON_SERVER)
!define ID1_ICON_SERVER(_alias, _label)                         ENTITY(rectangle,black,id1_icon_server,_label, _alias,ID1_ICON_SERVER)
!define ID1_ICON_SERVER(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_server,_label, _alias,ID1_ICON_SERVER)
!define ID1_ICON_SERVER(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_server,_label, _alias,ID1_ICON_SERVER
skinparam folderBackgroundColor<<ID1 ICON_SERVER>> White
@enduml
