@startuml
sprite $id1_icon_certificate [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF766666666666666666666667FFFFFFFFFFFF
FFFFFFFFFFFE5447AAAAAAAAAAAAAAAA6445EFFFFFFFFFFF
FFFFFFFFFFFE645BFFFFFFFFFFFFFFFFA546EFFFFFFFFFFF
FFFFFFFFFFFE66AFFFFFFFFFFFFFFFFFFA66EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFF7778888777FFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFF777755557777FFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFF77753222235777FFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFF7774222222224777FFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFF7752222222222577FFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFF7732222222422377FFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFF8522222224322258FFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFF8522222234222258FFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFF8522232252222258FFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFF8522244432222258FFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFF7732224422222377FFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFF7752222222222577FFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFF7774222222224777FFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFF77753222235777FFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFF777755557777FFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFF7778888777FFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE6BFFFFFFFFFFFFFFFFFFFFB6EFFFFFFFFFFF
FFFFFFFFFFFE66BFFFFFFFFFFFFFFFFFFA66EFFFFFFFFFFF
FFFFFFFFFFFE645BFFFFFFFFFFFFFFFFA546EFFFFFFFFFFF
FFFFFFFFFFFE5447AAAAAAAAAAAAAAAA6445EFFFFFFFFFFF
FFFFFFFFFFFF766666666666666666666667FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_CERTIFICATE(_color)                                 SPRITE_PUT(                                        id1_icon_certificate, _color)
!define ID1_ICON_CERTIFICATE(_color, _scale)                         SPRITE_PUT(                                        id1_icon_certificate, _color, _scale)
!define ID1_ICON_CERTIFICATE(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_CERTIFICATE,         id1_icon_certificate, _color, _scale)
!define ID1_ICON_CERTIFICATE(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_CERTIFICATE,         id1_icon_certificate, _color, _scale, _shape)
!define ID1_ICON_CERTIFICATE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_CERTIFICATE, _label, id1_icon_certificate, _color, _scale, _shape)
!define ID1_ICON_CERTIFICATE(_alias)                                 ENTITY(rectangle,black,id1_icon_certificate,_alias,ID1_ICON_CERTIFICATE)
!define ID1_ICON_CERTIFICATE(_alias, _label)                         ENTITY(rectangle,black,id1_icon_certificate,_label, _alias,ID1_ICON_CERTIFICATE)
!define ID1_ICON_CERTIFICATE(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_certificate,_label, _alias,ID1_ICON_CERTIFICATE)
!define ID1_ICON_CERTIFICATE(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_certificate,_label, _alias,ID1_ICON_CERTIFICATE
skinparam folderBackgroundColor<<ID1 ICON_CERTIFICATE>> White
@enduml
