@startuml
sprite $id1_icon_browser [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFD8888888888888888888888888888888888DFFFFFF
FFFFFFB6888888888888888888888888888888886BFFFFFF
FFFFFFB6B7BB7CB8DFFFFFFFFFFFFFFFFFFFFFFE6BFFFFFF
FFFFFFB6A6AA6B96CFFFFFFFFFFFFFFFFFFFFFFD6BFFFFFF
FFFFFFB6BBCCBCBBCCCCCCCCCCCCCCCCCCCCCCCB6BFFFFFF
FFFFFFB4344443443333333333333333333333334BFFFFFF
FFFFFFD4222222222222222222222222222222224DFFFFFF
FFFFFFD4222222222222222222222222222222224DFFFFFF
FFFFFFD4222222222222222222222222222222224DFFFFFF
FFFFFFB5555555555555555555555555555555555BFFFFFF
FFFFFFB6F888888888888888888888888888888F6BFFFFFF
FFFFFFB6DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD6BFFFFFF
FFFFFFB6DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD6BFFFFFF
FFFFFFB6DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD6BFFFFFF
FFFFFFB6DFFFFFFFFECCCCCCCCCCCCEFFFFFFFFD6BFFFFFF
FFFFFFB6DFFFFFFFFA666666666666AFFFFFFFFD6BFFFFFF
FFFFFFB6DFFFFFFFF96DDDDDDDDDD69FFFFFFFFD6BFFFFFF
FFFFFFB6DFFFFFFFF96BBBBBBBBBB69FFFFFFFFD6BFFFFFF
FFFFFFB6DFFFFFFFFB666666666666BFFFFFFFFD6BFFFFFF
FFFFFFB6DFFFFFFFFFEEEEEEEEEEEEFFFFFFFFFD6BFFFFFF
FFFFFFB6DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD6BFFFFFF
FFFFFFB6DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD6BFFFFFF
FFFFFFB6DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD6BFFFFFF
FFFFFFB6DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD6BFFFFFF
FFFFFFB6DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD6BFFFFFF
FFFFFFB6EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE6BFFFFFF
FFFFFFB6888888888888888888888888888888886BFFFFFF
FFFFFFD8888888888888888888888888888888888DFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_BROWSER(_color)                                 SPRITE_PUT(                                    id1_icon_browser, _color)
!define ID1_ICON_BROWSER(_color, _scale)                         SPRITE_PUT(                                    id1_icon_browser, _color, _scale)
!define ID1_ICON_BROWSER(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_BROWSER,         id1_icon_browser, _color, _scale)
!define ID1_ICON_BROWSER(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_BROWSER,         id1_icon_browser, _color, _scale, _shape)
!define ID1_ICON_BROWSER(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_BROWSER, _label, id1_icon_browser, _color, _scale, _shape)
!define ID1_ICON_BROWSER(_alias)                                 ENTITY(rectangle,black,id1_icon_browser,_alias,ID1_ICON_BROWSER)
!define ID1_ICON_BROWSER(_alias, _label)                         ENTITY(rectangle,black,id1_icon_browser,_label, _alias,ID1_ICON_BROWSER)
!define ID1_ICON_BROWSER(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_browser,_label, _alias,ID1_ICON_BROWSER)
!define ID1_ICON_BROWSER(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_browser,_label, _alias,ID1_ICON_BROWSER
skinparam folderBackgroundColor<<ID1 ICON_BROWSER>> White
@enduml
