@startuml
sprite $id1_icon_pipeline [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7777FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7677FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7458FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7458FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7458FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7677FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7777FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7667FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7458FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7458FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7557FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7777FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7777FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7567FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF7677FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF7778888777FFFFFFFFFFFFFFFFFFF
FFFFFFFD98889DFFFFFF96555569FFFFFFD98889DFFFFFFF
FFFFFFD7675667AAAAAB63433436BAAAAA6675667DFFFFFF
FFFFFF86DF96C65666664357466366666666C96C68FFFFFF
FFFFFD6AFEF69B6DFFFFA637647450FFFFE87E6AA6DFFFFF
FFFFFA6D77F87F6AFFFF9845737548BFFFFC6B87E6AFFFFF
FFFFF97B44BA6F78FFFF77647466477FFFFF79A6F79FFFFF
FFFFF88A449B6D88FFFFF7647457377FFFFF88B6E88FFFFF
FFFFF889449C6D87FFFFF7647457377FFFFF88C6D88FFFFF
FFFFF88A449C6D88FFFFF7647457377FFFFF88B6E88FFFFF
FFFFF97B44BA6F78FFFF78547466477FFFFF79A6F79FFFFF
FFFFFA6D66E87F6AFFFF874573754AEFFFFC6C87E6AFFFFF
FFFFFD6ADDF69B6BCCCC854764745FCCCCC77E6AA6DFFFFF
FFFFFF86EF96C65666664377466366666657D96C68FFFFFF
FFFFFFD7675667BCCCCD63433436ECCCCB7675667DFFFFFF
FFFFFFFD98889DFFFFFDA6555568EFFFFFD98889DFFFFFFF
FFFFFFFFFFFFFFFFFFF7778888777FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID1_ICON_PIPELINE(_color)                                 SPRITE_PUT(                                     id1_icon_pipeline, _color)
!define ID1_ICON_PIPELINE(_color, _scale)                         SPRITE_PUT(                                     id1_icon_pipeline, _color, _scale)
!define ID1_ICON_PIPELINE(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID1 ICON_PIPELINE,         id1_icon_pipeline, _color, _scale)
!define ID1_ICON_PIPELINE(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID1 ICON_PIPELINE,         id1_icon_pipeline, _color, _scale, _shape)
!define ID1_ICON_PIPELINE(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID1 ICON_PIPELINE, _label, id1_icon_pipeline, _color, _scale, _shape)
!define ID1_ICON_PIPELINE(_alias)                                 ENTITY(rectangle,black,id1_icon_pipeline,_alias,ID1_ICON_PIPELINE)
!define ID1_ICON_PIPELINE(_alias, _label)                         ENTITY(rectangle,black,id1_icon_pipeline,_label, _alias,ID1_ICON_PIPELINE)
!define ID1_ICON_PIPELINE(_alias, _label, _shape)                 ENTITY(_shape,black,id1_icon_pipeline,_label, _alias,ID1_ICON_PIPELINE)
!define ID1_ICON_PIPELINE(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id1_icon_pipeline,_label, _alias,ID1_ICON_PIPELINE
skinparam folderBackgroundColor<<ID1 ICON_PIPELINE>> White
@enduml
