@startuml
sprite $id2_icon_getting_started [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF555555FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF55555555FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF555555555FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF5555555555FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF55555555555FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF55555555555FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF555555555555FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF5555555555555FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF55555555555555FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF555555555555555FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF5555555555555555FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF5555555555555555FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF55555555555555555FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF55555555555555555FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF555555555555555555555555555555555FFFF
FFFFFFFFFF55555555555555555555555555555555555FFF
FFFFFFFFF555555555555555555555555555555555555FFF
FFFFFFFF5555555555555555555555555555555555555FFF
FFFFFFF55555555555555555555555555555555555555FFF
FFFFFF555555555555555555555555555555555555555FFF
FFFFF5555555555555555555555555555555555555555FFF
FFFFF555555555555555555555555555555555555555FFFF
FFFF5555555555555555555555555555555555555555FFFF
FFF5555555555555555555555555555555555555555FFFFF
FFF555555555555555555555555555555555555555FFFFFF
FFF55555555555555555555555555555555555555FFFFFFF
FFF5555555555555555555555555555555555555FFFFFFFF
FFF555555555555555555555555555555555555FFFFFFFFF
FFF55555555555555555555555555555555555FFFFFFFFFF
FFFF5555555555555555555555555555555555FFFFFFFFFF
FFFFFFFFFFFFFFFFFFF555555555555555555FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF55555555555555555FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF5555555555555555FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF555555555555555FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF555555555555555FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF55555555555555FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF5555555555555FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF5555555555555FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF555555555555FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF55555555555FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF5555555555FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF555555555FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF55555555FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF555555FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID2_ICON_GETTING_STARTED(_color)                                 SPRITE_PUT(                                            id2_icon_getting_started, _color)
!define ID2_ICON_GETTING_STARTED(_color, _scale)                         SPRITE_PUT(                                            id2_icon_getting_started, _color, _scale)
!define ID2_ICON_GETTING_STARTED(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID2 ICON_GETTING_STARTED,         id2_icon_getting_started, _color, _scale)
!define ID2_ICON_GETTING_STARTED(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID2 ICON_GETTING_STARTED,         id2_icon_getting_started, _color, _scale, _shape)
!define ID2_ICON_GETTING_STARTED(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID2 ICON_GETTING_STARTED, _label, id2_icon_getting_started, _color, _scale, _shape)
!define ID2_ICON_GETTING_STARTED(_alias)                                 ENTITY(rectangle,black,id2_icon_getting_started,_alias,ID2_ICON_GETTING_STARTED)
!define ID2_ICON_GETTING_STARTED(_alias, _label)                         ENTITY(rectangle,black,id2_icon_getting_started,_label, _alias,ID2_ICON_GETTING_STARTED)
!define ID2_ICON_GETTING_STARTED(_alias, _label, _shape)                 ENTITY(_shape,black,id2_icon_getting_started,_label, _alias,ID2_ICON_GETTING_STARTED)
!define ID2_ICON_GETTING_STARTED(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id2_icon_getting_started,_label, _alias,ID2_ICON_GETTING_STARTED
skinparam folderBackgroundColor<<ID2 ICON_GETTING_STARTED>> White
@enduml
