@startuml
sprite $id2_icon_efficiency [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF555555555FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF55555555555FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF55555555555FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF55555555555FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF55555555555FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF5555555555FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF5555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF5555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF5555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF55555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF555555555555555555555555FFFFFFFFFFFFFFF
FFFFFFFFF555555555555555555555555FFFFFFFFFFFFFFF
FFFFFFFFF555555555555555555555555FFFFFFFFFFFFFFF
FFFFFFFFF555555555555555555555555FFFFFFFFFFFFFFF
FFFFFFFFF555555555555555555555555FFFFFFFFFFFFFFF
FFFFFFFFFF55555555555555555555555FFFFFFFFFFFFFFF
FFFFFFFFFF555555555F555555555555FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF5555555555555FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF5555555555555FFFFFFFFFFFFFFF
FFFFFF1111111FFFFFFF5555555555555FF1111111FFFFFF
FFFFF111111111FFFFFF5555555555555F111111111FFFFF
FFFF11111111111FFFFF555555555555511111111111FFFF
FFFF11111111111FFFFF555555F55555511111111111FFFF
FFFF11111111111FFFFFFFFFFFF55555511111111111FFFF
FFFF11111111111FFFFFFFFFFFF55555511111111111FFFF
FFFF11111111111FFFFFFFFFFFF55555511111111111FFFF
FFFF11111111111FFFFFFFFFFF555555511111111111FFFF
FFFF11111111111FFFFFFFFFFF555555511111111111FFFF
FFFFF1111111111FFFFFFFFFF555555551111111111FFFFF
FFFFFF11111111FFFFFFFFFF555555555F111111111FFFFF
FFFFFFFFFFFFFFFFFFFFFFF5555555555FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF5555555555FFFFFFFFFFFFFFFF
FFFFFFFFFF555555555FF55555555541111111FFFFFFFFFF
FFFFFFFFFF5555555555F55555555411111111FFFFFFFFFF
FFFFFFFFF55555555555F555555551111111111FFFFFFFFF
FFFFFFFFF55555555555F555555511111111111FFFFFFFFF
FFFFFFFFF55555555555F555555511111111111FFFFFFFFF
FFFFFFFFF55555555555FF55555F11111111111FFFFFFFFF
FFFFFFFFF55555555555FFFFFFFF11111111111FFFFFFFFF
FFFFFFFFF55555555555FFFFFFFF11111111111FFFFFFFFF
FFFFFFFFFF5555555555FFFFFFFF1111111111FFFFFFFFFF
FFFFFFFFFF555555555FFFFFFFFFF111111111FFFFFFFFFF
FFFFFFFFFFFF555555FFFFFFFFFFFF111111FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID2_ICON_EFFICIENCY(_color)                                 SPRITE_PUT(                                       id2_icon_efficiency, _color)
!define ID2_ICON_EFFICIENCY(_color, _scale)                         SPRITE_PUT(                                       id2_icon_efficiency, _color, _scale)
!define ID2_ICON_EFFICIENCY(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID2 ICON_EFFICIENCY,         id2_icon_efficiency, _color, _scale)
!define ID2_ICON_EFFICIENCY(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID2 ICON_EFFICIENCY,         id2_icon_efficiency, _color, _scale, _shape)
!define ID2_ICON_EFFICIENCY(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID2 ICON_EFFICIENCY, _label, id2_icon_efficiency, _color, _scale, _shape)
!define ID2_ICON_EFFICIENCY(_alias)                                 ENTITY(rectangle,black,id2_icon_efficiency,_alias,ID2_ICON_EFFICIENCY)
!define ID2_ICON_EFFICIENCY(_alias, _label)                         ENTITY(rectangle,black,id2_icon_efficiency,_label, _alias,ID2_ICON_EFFICIENCY)
!define ID2_ICON_EFFICIENCY(_alias, _label, _shape)                 ENTITY(_shape,black,id2_icon_efficiency,_label, _alias,ID2_ICON_EFFICIENCY)
!define ID2_ICON_EFFICIENCY(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id2_icon_efficiency,_label, _alias,ID2_ICON_EFFICIENCY
skinparam folderBackgroundColor<<ID2 ICON_EFFICIENCY>> White
@enduml
