@startuml
sprite $id2_icon_branding [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF888888FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF888877888FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF88887532488FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF888753222378FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8886322222378FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF888853222222488FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8887522222222688FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF8887422222222488FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF88874222222222688FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF888732222222224888FFF
FFFFFFFFFFFFFFFFFFFFFFFFFF888732222222222688FFFF
FFFFFFFFFFFFFFFFFFFFFFFFF8887322222222225888FFFF
FFFFFFFFFFFFFFFFFFFFFFFF8887322222222223788FFFFF
FFFFFFFFFFFFFFFFFFFFFFF8887322222222222688FFFFFF
FFFFFFFFFFFFFFFFFFFFFFF8874222222222225888FFFFFF
FFFFFFFFFFFFFFFFFFFFFF8874222222222224788FFFFFFF
FFFFFFFFFFFFFFFFFFFFF8884222222222223788FFFFFFFF
FFFFFFFFFFFFFFFFFFFF88852222222222226888FFFFFFFF
FFFFFFFFFFFFFFFFFFF88862222222222225888FFFFFFFFF
FFFFFFFFFFFFFFFFFF88862222222222224888FFFFFFFFFF
FFFFFFFFFFFFFFFFFF8873222222222224788FFFFFFFFFFF
FFFFFFFFFFFFFFFFF8874222222222223788FFFFFFFFFFFF
FFFFFFFFFFFFFFFFF8852222222222237888FFFFFFFFFFFF
FFFFFFFFFFFFF5555787422222222236888FFFFFFFFFFFFF
FFFFFFFFFFF555555557A6322222226888FFFFFFFFFFFFFF
FFFFFFFFFF55543223455863222226888FFFFFFFFFFFFFFF
FFFFFFFFF55531000012458732226888FFFFFFFFFFFFFFFF
FFFFFFFFF4531000000014586325888FFFFFFFFFFFFFFFFF
FFFFFFFF5541000000000145866888FFFFFFFFFFFFFFFFFF
FFFFFFFF552000000000002568888FFFFFFFFFFFFFFFFFFF
FFFFFFF554100000000000145888FFFFFFFFFFFFFFFFFFFF
FFFFFFF5530000000000000355FFFFFFFFFFFFFFFFFFFFFF
FFFFFFF5510000000000000255FFFFFFFFFFFFFFFFFFFFFF
FFFFFF55410000000000000255FFFFFFFFFFFFFFFFFFFFFF
FFFFFF55300000000000000255FFFFFFFFFFFFFFFFFFFFFF
FFFFF555100000000000000355FFFFFFFFFFFFFFFFFFFFFF
FFFF555300000000000000155FFFFFFFFFFFFFFFFFFFFFFF
FFF5554100000000000001355FFFFFFFFFFFFFFFFFFFFFFF
FF55552000000000000013555FFFFFFFFFFFFFFFFFFFFFFF
FF5541000000000000124555FFFFFFFFFFFFFFFFFFFFFFFF
FF552000000000011245555FFFFFFFFFFFFFFFFFFFFFFFFF
FF55432111111234555555FFFFFFFFFFFFFFFFFFFFFFFFFF
FF555555444555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF555555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID2_ICON_BRANDING(_color)                                 SPRITE_PUT(                                     id2_icon_branding, _color)
!define ID2_ICON_BRANDING(_color, _scale)                         SPRITE_PUT(                                     id2_icon_branding, _color, _scale)
!define ID2_ICON_BRANDING(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID2 ICON_BRANDING,         id2_icon_branding, _color, _scale)
!define ID2_ICON_BRANDING(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID2 ICON_BRANDING,         id2_icon_branding, _color, _scale, _shape)
!define ID2_ICON_BRANDING(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID2 ICON_BRANDING, _label, id2_icon_branding, _color, _scale, _shape)
!define ID2_ICON_BRANDING(_alias)                                 ENTITY(rectangle,black,id2_icon_branding,_alias,ID2_ICON_BRANDING)
!define ID2_ICON_BRANDING(_alias, _label)                         ENTITY(rectangle,black,id2_icon_branding,_label, _alias,ID2_ICON_BRANDING)
!define ID2_ICON_BRANDING(_alias, _label, _shape)                 ENTITY(_shape,black,id2_icon_branding,_label, _alias,ID2_ICON_BRANDING)
!define ID2_ICON_BRANDING(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id2_icon_branding,_label, _alias,ID2_ICON_BRANDING
skinparam folderBackgroundColor<<ID2 ICON_BRANDING>> White
@enduml
