@startuml
sprite $id2_icon_efficiency [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF888888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF887788888FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF87335788888FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF87322245788FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF87322223688FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF87323467888FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF8734788888FFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF8735888FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF8887358888FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF8874235788FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF88732222488FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF884235522688888888888888FFFFFFFFFFFFFFF
FFFFFFFFF883258842588877777777788FFFFFFFFFFFFFFF
FFFFFFFFF883258732588842222222378FFFFFFFFFFFFFFF
FFFFFFFFF885224322788732222222268FFFFFFFFFFFFFFF
FFFFFFFFF887422225888732222355688FFFFFFFFFFFFFFF
FFFFFFFFFF88865578888732332258888FFFFFFFFFFFFFFF
FFFFFFFFFF888888888F873246322688FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF8732486223788FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF8732488522688FFFFFFFFFFFFFFF
FFFFFF5555555FFFFFFF8732488732488FF5555555FFFFFF
FFFFF555555555FFFFFF8842588842378F555555555FFFFF
FFFF55532113555FFFFF887788886226855531123555FFFF
FFFF55310100255FFFFF888888F87225855300101355FFFF
FFFF55202431145FFFFFFFFFFFF87325854113420155FFFF
FFFF55114551045FFFFFFFFFFFF87325854115541145FFFF
FFFF55103541145FFFFFFFFFFFF87225854114530155FFFF
FFFF55301110255FFFFFFFFFFF886226855201110355FFFF
FFFF55531012455FFFFFFFFFFF884227855521012555FFFF
FFFFF5554445555FFFFFFFFFF887324885555444555FFFFF
FFFFFF55555555FFFFFFFFFF888522588F555555555FFFFF
FFFFFFFFFFFFFFFFFFFFFFF8886223788FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF8887322688FFFFFFFFFFFFFFFF
FFFFFFFFFF888888888FF88863225875555555FFFFFFFFFF
FFFFFFFFFF8886556888F88522248754334555FFFFFFFFFF
FFFFFFFFF88742222588F884225885310012555FFFFFFFFF
FFFFFFFFF88522432278F886468854102210355FFFFFFFFF
FFFFFFFFF88325873258F888888853025530255FFFFFFFFF
FFFFFFFFF88325884258FF88888F53025530155FFFFFFFFF
FFFFFFFFF88523542268FFFFFFFF54112310255FFFFFFFFF
FFFFFFFFF88732222488FFFFFFFF55310001455FFFFFFFFF
FFFFFFFFFF8875345888FFFFFFFF5553223555FFFFFFFFFF
FFFFFFFFFF888888888FFFFFFFFFF555555555FFFFFFFFFF
FFFFFFFFFFFF888888FFFFFFFFFFFF555555FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID2_ICON_EFFICIENCY(_color)                                 SPRITE_PUT(                                       id2_icon_efficiency, _color)
!define ID2_ICON_EFFICIENCY(_color, _scale)                         SPRITE_PUT(                                       id2_icon_efficiency, _color, _scale)
!define ID2_ICON_EFFICIENCY(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID2 ICON_EFFICIENCY,         id2_icon_efficiency, _color, _scale)
!define ID2_ICON_EFFICIENCY(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID2 ICON_EFFICIENCY,         id2_icon_efficiency, _color, _scale, _shape)
!define ID2_ICON_EFFICIENCY(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID2 ICON_EFFICIENCY, _label, id2_icon_efficiency, _color, _scale, _shape)
!define ID2_ICON_EFFICIENCY(_alias)                                 ENTITY(rectangle,black,id2_icon_efficiency,_alias,ID2_ICON_EFFICIENCY)
!define ID2_ICON_EFFICIENCY(_alias, _label)                         ENTITY(rectangle,black,id2_icon_efficiency,_label, _alias,ID2_ICON_EFFICIENCY)
!define ID2_ICON_EFFICIENCY(_alias, _label, _shape)                 ENTITY(_shape,black,id2_icon_efficiency,_label, _alias,ID2_ICON_EFFICIENCY)
!define ID2_ICON_EFFICIENCY(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id2_icon_efficiency,_label, _alias,ID2_ICON_EFFICIENCY
skinparam folderBackgroundColor<<ID2 ICON_EFFICIENCY>> White
@enduml
