@startuml
sprite $id2_icon_pipeline_a [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF88888888888888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF8887777777777888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF8853222222222488FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF8732222222222268FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF8732222222222268FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF8853222222222488FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF8886222222226888FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF88722222222688FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF872222222268FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF872222222268FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF872222222268FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF872222222268FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF872222222268FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF872222222268FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF872222222268FF888888FFFFFFFFFFFFFFFFFFFFFFFF
FFFF872222222268888877888FFFFFFFFFFFFFFFFFFFFFFF
FFFF873222222258888533588555555555555FFFFFFFFFFF
FFFF87322222222567632237855444444555555FFFFFFFFF
FFFF884222222222222222278541111111245555FFFFFFFF
FFFF8862222222222222222785410000000124555FFFFFFF
FFFFF8842222222222222227854100000000013555FFFFFF
FFFFF88632222222222222278541000000000013555FFFFF
FFFFF88862222222222222278541000000000001355FFFFF
FFFFFF88863222222222222785410000000000001555FFFF
FFFFFFF8886422222222222785410000000000000355FFFF
FFFFFFFF888864332222222785411111000000000255FFFF
FFFFFFFFF88888777762222785544444310000000145FFFF
FFFFFFFFFFFF88888884224885555555541000000145FFFF
FFFFFFFFFFFFFFFFF88866888FFFFFF5551000000045FFFF
FFFFFFFFFFFFFFFFFF888888FFFFFFFF551000000045FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF551000000045FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF551000000045FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF551000000045FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF551000000045FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF551000000045FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF551000000045FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF555100000004555FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5554100000003555FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5531000000001255FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5510000000000145FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5510000000000145FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5531111111111255FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5555444444444555FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF555555555555555FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID2_ICON_PIPELINE_A(_color)                                 SPRITE_PUT(                                       id2_icon_pipeline_a, _color)
!define ID2_ICON_PIPELINE_A(_color, _scale)                         SPRITE_PUT(                                       id2_icon_pipeline_a, _color, _scale)
!define ID2_ICON_PIPELINE_A(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID2 ICON_PIPELINE_A,         id2_icon_pipeline_a, _color, _scale)
!define ID2_ICON_PIPELINE_A(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID2 ICON_PIPELINE_A,         id2_icon_pipeline_a, _color, _scale, _shape)
!define ID2_ICON_PIPELINE_A(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID2 ICON_PIPELINE_A, _label, id2_icon_pipeline_a, _color, _scale, _shape)
!define ID2_ICON_PIPELINE_A(_alias)                                 ENTITY(rectangle,black,id2_icon_pipeline_a,_alias,ID2_ICON_PIPELINE_A)
!define ID2_ICON_PIPELINE_A(_alias, _label)                         ENTITY(rectangle,black,id2_icon_pipeline_a,_label, _alias,ID2_ICON_PIPELINE_A)
!define ID2_ICON_PIPELINE_A(_alias, _label, _shape)                 ENTITY(_shape,black,id2_icon_pipeline_a,_label, _alias,ID2_ICON_PIPELINE_A)
!define ID2_ICON_PIPELINE_A(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id2_icon_pipeline_a,_label, _alias,ID2_ICON_PIPELINE_A
skinparam folderBackgroundColor<<ID2 ICON_PIPELINE_A>> White
@enduml
