@startuml
sprite $id2_icon_pipeline_a [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF55555555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF5555555555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF5555555555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF5555555555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF5555555555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF5555555555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FF5555555555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF55555555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF555555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF555555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF555555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF555555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF555555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF555555555555FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF555555555555FF555555FFFFFFFFFFFFFFFFFFFFFFFF
FFFF555555555555555555555FFFFFFFFFFFFFFFFFFFFFFF
FFFF555555555555555555555111111111111FFFFFFFFFFF
FFFF55555555555555555555511111111111111FFFFFFFFF
FFFF555555555555555555555111111111111111FFFFFFFF
FFFF5555555555555555555551111111111111111FFFFFFF
FFFFF5555555555555555555511111111111111111FFFFFF
FFFFF55555555555555555555111111111111111111FFFFF
FFFFF55555555555555555555111111111111111111FFFFF
FFFFFF55555555555555555551111111111111111111FFFF
FFFFFFF5555555555555555551111111111111111111FFFF
FFFFFFFF555555555555555551111111111111111111FFFF
FFFFFFFFF55555555555555551111111111111111111FFFF
FFFFFFFFFFFF55555555555551111111111111111111FFFF
FFFFFFFFFFFFFFFFF55555555FFFFFF1111111111111FFFF
FFFFFFFFFFFFFFFFFF555555FFFFFFFF111111111111FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF111111111111FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF111111111111FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF111111111111FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF111111111111FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF111111111111FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF111111111111FFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF111111111111111FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1111111111111111FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1111111111111111FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1111111111111111FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1111111111111111FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1111111111111111FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1111111111111111FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF111111111111111FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID2_ICON_PIPELINE_A(_color)                                 SPRITE_PUT(                                       id2_icon_pipeline_a, _color)
!define ID2_ICON_PIPELINE_A(_color, _scale)                         SPRITE_PUT(                                       id2_icon_pipeline_a, _color, _scale)
!define ID2_ICON_PIPELINE_A(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID2 ICON_PIPELINE_A,         id2_icon_pipeline_a, _color, _scale)
!define ID2_ICON_PIPELINE_A(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID2 ICON_PIPELINE_A,         id2_icon_pipeline_a, _color, _scale, _shape)
!define ID2_ICON_PIPELINE_A(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID2 ICON_PIPELINE_A, _label, id2_icon_pipeline_a, _color, _scale, _shape)
!define ID2_ICON_PIPELINE_A(_alias)                                 ENTITY(rectangle,black,id2_icon_pipeline_a,_alias,ID2_ICON_PIPELINE_A)
!define ID2_ICON_PIPELINE_A(_alias, _label)                         ENTITY(rectangle,black,id2_icon_pipeline_a,_label, _alias,ID2_ICON_PIPELINE_A)
!define ID2_ICON_PIPELINE_A(_alias, _label, _shape)                 ENTITY(_shape,black,id2_icon_pipeline_a,_label, _alias,ID2_ICON_PIPELINE_A)
!define ID2_ICON_PIPELINE_A(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id2_icon_pipeline_a,_label, _alias,ID2_ICON_PIPELINE_A
skinparam folderBackgroundColor<<ID2 ICON_PIPELINE_A>> White
@enduml
