@startuml
sprite $id2_icon_branding [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF555555FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF555555555FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF55555555555FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF555555555555FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5555555555555FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF555555555555555FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5555555555555555FF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF5555555555555555FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFF55555555555555555FFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF555555555555555555FFF
FFFFFFFFFFFFFFFFFFFFFFFFFF555555555555555555FFFF
FFFFFFFFFFFFFFFFFFFFFFFFF5555555555555555555FFFF
FFFFFFFFFFFFFFFFFFFFFFFF5555555555555555555FFFFF
FFFFFFFFFFFFFFFFFFFFFFF5555555555555555555FFFFFF
FFFFFFFFFFFFFFFFFFFFFFF5555555555555555555FFFFFF
FFFFFFFFFFFFFFFFFFFFFF5555555555555555555FFFFFFF
FFFFFFFFFFFFFFFFFFFFF5555555555555555555FFFFFFFF
FFFFFFFFFFFFFFFFFFFF55555555555555555555FFFFFFFF
FFFFFFFFFFFFFFFFFFF55555555555555555555FFFFFFFFF
FFFFFFFFFFFFFFFFFF55555555555555555555FFFFFFFFFF
FFFFFFFFFFFFFFFFFF5555555555555555555FFFFFFFFFFF
FFFFFFFFFFFFFFFFF5555555555555555555FFFFFFFFFFFF
FFFFFFFFFFFFFFFFF5555555555555555555FFFFFFFFFFFF
FFFFFFFFFFFFF1111455555555555555555FFFFFFFFFFFFF
FFFFFFFFFFF11111111475555555555555FFFFFFFFFFFFFF
FFFFFFFFFF11111111112555555555555FFFFFFFFFFFFFFF
FFFFFFFFF11211111111115555555555FFFFFFFFFFFFFFFF
FFFFFFFFF0111111111111155555555FFFFFFFFFFFFFFFFF
FFFFFFFF1111111111111111555555FFFFFFFFFFFFFFFFFF
FFFFFFFF111111111111111125555FFFFFFFFFFFFFFFFFFF
FFFFFFF111111111111111111555FFFFFFFFFFFFFFFFFFFF
FFFFFFF1111111111111111111FFFFFFFFFFFFFFFFFFFFFF
FFFFFFF1111111111111111111FFFFFFFFFFFFFFFFFFFFFF
FFFFFF11111111111111111111FFFFFFFFFFFFFFFFFFFFFF
FFFFFF11111111111111111111FFFFFFFFFFFFFFFFFFFFFF
FFFFF111111111111111111111FFFFFFFFFFFFFFFFFFFFFF
FFFF111111111111111111111FFFFFFFFFFFFFFFFFFFFFFF
FFF1111111111111111111111FFFFFFFFFFFFFFFFFFFFFFF
FF11111111111111111111111FFFFFFFFFFFFFFFFFFFFFFF
FF1111111111111111111111FFFFFFFFFFFFFFFFFFFFFFFF
FF111111111111111111111FFFFFFFFFFFFFFFFFFFFFFFFF
FF11111111111111111111FFFFFFFFFFFFFFFFFFFFFFFFFF
FF111111111111111111FFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFF111111111111FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID2_ICON_BRANDING(_color)                                 SPRITE_PUT(                                     id2_icon_branding, _color)
!define ID2_ICON_BRANDING(_color, _scale)                         SPRITE_PUT(                                     id2_icon_branding, _color, _scale)
!define ID2_ICON_BRANDING(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID2 ICON_BRANDING,         id2_icon_branding, _color, _scale)
!define ID2_ICON_BRANDING(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID2 ICON_BRANDING,         id2_icon_branding, _color, _scale, _shape)
!define ID2_ICON_BRANDING(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID2 ICON_BRANDING, _label, id2_icon_branding, _color, _scale, _shape)
!define ID2_ICON_BRANDING(_alias)                                 ENTITY(rectangle,black,id2_icon_branding,_alias,ID2_ICON_BRANDING)
!define ID2_ICON_BRANDING(_alias, _label)                         ENTITY(rectangle,black,id2_icon_branding,_label, _alias,ID2_ICON_BRANDING)
!define ID2_ICON_BRANDING(_alias, _label, _shape)                 ENTITY(_shape,black,id2_icon_branding,_label, _alias,ID2_ICON_BRANDING)
!define ID2_ICON_BRANDING(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id2_icon_branding,_label, _alias,ID2_ICON_BRANDING
skinparam folderBackgroundColor<<ID2 ICON_BRANDING>> White
@enduml
