@startuml
sprite $id2_icon_getting_started [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF888888FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF88877888FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF888633588FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFF8886222268FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF88863222268FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF88732222278FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF887322222378FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF8874222222388FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF88852222222488FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF888522222222488FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFF8886222222222588FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFF8886322222222268FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF88873222222222268FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF88732222222222378FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF887422222222222378888888888888888FFFF
FFFFFFFFFF88842222222222223666666666666667888FFF
FFFFFFFFF888522222222222222222222222222222488FFF
FFFFFFFF8885222222222222222222222222222222268FFF
FFFFFFF88862222222222222222222222222222222268FFF
FFFFFF888632222222222222222222222222222222488FFF
FFFFF8887322222222222222222222222222222224788FFF
FFFFF887322222222222222222222222222222223788FFFF
FFFF8874222222222222222222222222222222237888FFFF
FFF8885222222222222222222222222222222226888FFFFF
FFF885222222222222222222222222222222226888FFFFFF
FFF87322222222222222222222222222222225888FFFFFFF
FFF8732222222222222222222222222222225888FFFFFFFF
FFF885222222222222222222222222222224788FFFFFFFFF
FFF88876666666666666642222222222223788FFFFFFFFFF
FFFF8888888888888888842222222222237888FFFFFFFFFF
FFFFFFFFFFFFFFFFFFF883222222222236888FFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF87322222222226888FFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF8722222222225888FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF862222222225888FFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF885222222224888FFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF88522222224788FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF8842222223788FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF8832222237888FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF873222236888FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF87222226888FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF8732225888FFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF885325888FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF88877888FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF888888FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

!define ID2_ICON_GETTING_STARTED(_color)                                 SPRITE_PUT(                                            id2_icon_getting_started, _color)
!define ID2_ICON_GETTING_STARTED(_color, _scale)                         SPRITE_PUT(                                            id2_icon_getting_started, _color, _scale)
!define ID2_ICON_GETTING_STARTED(_color, _scale, _alias)                 SPRITE_ENT(  _alias, ID2 ICON_GETTING_STARTED,         id2_icon_getting_started, _color, _scale)
!define ID2_ICON_GETTING_STARTED(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, ID2 ICON_GETTING_STARTED,         id2_icon_getting_started, _color, _scale, _shape)
!define ID2_ICON_GETTING_STARTED(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, ID2 ICON_GETTING_STARTED, _label, id2_icon_getting_started, _color, _scale, _shape)
!define ID2_ICON_GETTING_STARTED(_alias)                                 ENTITY(rectangle,black,id2_icon_getting_started,_alias,ID2_ICON_GETTING_STARTED)
!define ID2_ICON_GETTING_STARTED(_alias, _label)                         ENTITY(rectangle,black,id2_icon_getting_started,_label, _alias,ID2_ICON_GETTING_STARTED)
!define ID2_ICON_GETTING_STARTED(_alias, _label, _shape)                 ENTITY(_shape,black,id2_icon_getting_started,_label, _alias,ID2_ICON_GETTING_STARTED)
!define ID2_ICON_GETTING_STARTED(_alias, _label, _shape, _color)         ENTITY(_shape,_color,id2_icon_getting_started,_label, _alias,ID2_ICON_GETTING_STARTED
skinparam folderBackgroundColor<<ID2 ICON_GETTING_STARTED>> White
@enduml
